% utf82gr.pat

@patterns 0

% punctuation

";" p "<GR>;</GR>"
"·" p "<GR>&middot;</GR>"
"ʼ" p "<GR>&apos;</GR>"
"′" p "<GR>&prime;</GR>"

% basic Greek alphabet.

"Α" p "<GR>A</GR>"
"Β" p "<GR>B</GR>"
"Γ" p "<GR>G</GR>"
"Δ" p "<GR>D</GR>"
"Ε" p "<GR>E</GR>"
"Ζ" p "<GR>Z</GR>"
"Η" p "<GR>H</GR>"
"Θ" p "<GR>J</GR>"
"Ι" p "<GR>I</GR>"
"Κ" p "<GR>K</GR>"
"Λ" p "<GR>L</GR>"
"Μ" p "<GR>M</GR>"
"Ν" p "<GR>N</GR>"
"Ξ" p "<GR>X</GR>"
"Ο" p "<GR>O</GR>"
"Π" p "<GR>P</GR>"
"Ρ" p "<GR>R</GR>"
"Σ" p "<GR>S</GR>"
"Τ" p "<GR>T</GR>"
"Υ" p "<GR>U</GR>"
"Φ" p "<GR>F</GR>"
"Χ" p "<GR>Q</GR>"
"Ψ" p "<GR>Y</GR>"
"Ω" p "<GR>W</GR>"

"α" p "<GR>a</GR>"
"β" p "<GR>b</GR>"
"γ" p "<GR>g</GR>"
"δ" p "<GR>d</GR>"
"ε" p "<GR>e</GR>"
"ζ" p "<GR>z</GR>"
"η" p "<GR>h</GR>"
"θ" p "<GR>j</GR>"
"ϑ" p "<GR>j</GR>"
"ι" p "<GR>i</GR>"
"κ" p "<GR>k</GR>"
"λ" p "<GR>l</GR>"
"μ" p "<GR>m</GR>"
"ν" p "<GR>n</GR>"
"ξ" p "<GR>x</GR>"
"ο" p "<GR>o</GR>"
"π" p "<GR>p</GR>"
"ρ" p "<GR>r</GR>"
"ς" p "<GR>c</GR>"
"σ" p "<GR>s</GR>"
"τ" p "<GR>t</GR>"
"υ" p "<GR>u</GR>"
"φ" p "<GR>f</GR>"
"χ" p "<GR>q</GR>"
"ψ" p "<GR>y</GR>"
"ω" p "<GR>w</GR>"

% Greek extended

"ἀ" p "<GR>>a</GR>"
"ἁ" p "<GR><a</GR>"
"ἂ" p "<GR>>`a</GR>"
"ἃ" p "<GR><`a</GR>"
"ἄ" p "<GR>>'a</GR>"
"ἅ" p "<GR><'a</GR>"
"ἆ" p "<GR>>=a</GR>"
"ἇ" p "<GR><=a</GR>"
"Ἀ" p "<GR>>A</GR>"
"Ἁ" p "<GR><A</GR>"
"Ἂ" p "<GR>>`A</GR>"
"Ἃ" p "<GR><`A</GR>"
"Ἄ" p "<GR>>'A</GR>"
"Ἅ" p "<GR><'A</GR>"
"Ἆ" p "<GR>>=A</GR>"
"Ἇ" p "<GR><=A</GR>"

"ἐ" p "<GR>>e</GR>"
"ἑ" p "<GR><e</GR>"
"ἒ" p "<GR>>`e</GR>"
"ἓ" p "<GR><`e</GR>"
"ἔ" p "<GR>>'e</GR>"
"ἕ" p "<GR><'e</GR>"
"Ἐ" p "<GR>>E</GR>"
"Ἑ" p "<GR><E</GR>"
"Ἒ" p "<GR>>`E</GR>"
"Ἓ" p "<GR><`E</GR>"
"Ἔ" p "<GR>>'E</GR>"
"Ἕ" p "<GR><'E</GR>"

"ἠ" p "<GR>>h</GR>"
"ἡ" p "<GR><h</GR>"
"ἢ" p "<GR>>`h</GR>"
"ἣ" p "<GR><`h</GR>"
"ἤ" p "<GR>>'h</GR>"
"ἥ" p "<GR><'h</GR>"
"ἦ" p "<GR>>=h</GR>"
"ἧ" p "<GR><=h</GR>"
"Ἠ" p "<GR>>H</GR>"
"Ἡ" p "<GR><H</GR>"
"Ἢ" p "<GR>>`H</GR>"
"Ἣ" p "<GR><`H</GR>"
"Ἤ" p "<GR>>'H</GR>"
"Ἥ" p "<GR><'H</GR>"
"Ἦ" p "<GR>>=H</GR>"
"Ἧ" p "<GR><=H</GR>"

"ἰ" p "<GR>>i</GR>"
"ἱ" p "<GR><i</GR>"
"ἲ" p "<GR>>`i</GR>"
"ἳ" p "<GR><`i</GR>"
"ἴ" p "<GR>>'i</GR>"
"ἵ" p "<GR><'i</GR>"
"ἶ" p "<GR>>=i</GR>"
"ἷ" p "<GR><=i</GR>"
"Ἰ" p "<GR>>I</GR>"
"Ἱ" p "<GR><I</GR>"
"Ἲ" p "<GR>>`I</GR>"
"Ἳ" p "<GR><`I</GR>"
"Ἴ" p "<GR>>'I</GR>"
"Ἵ" p "<GR><'I</GR>"
"Ἶ" p "<GR>>=I</GR>"
"Ἷ" p "<GR><=I</GR>"

"ὀ" p "<GR>>o</GR>"
"ὁ" p "<GR><o</GR>"
"ὂ" p "<GR>>`o</GR>"
"ὃ" p "<GR><`o</GR>"
"ὄ" p "<GR>>'o</GR>"
"ὅ" p "<GR><'o</GR>"
"Ὀ" p "<GR>>O</GR>"
"Ὁ" p "<GR><O</GR>"
"Ὂ" p "<GR>>`O</GR>"
"Ὃ" p "<GR><`O</GR>"
"Ὄ" p "<GR>>'O</GR>"
"Ὅ" p "<GR><'O</GR>"

"ὐ" p "<GR>>u</GR>"
"ὑ" p "<GR><u</GR>"
"ὒ" p "<GR>>`u</GR>"
"ὓ" p "<GR><`u</GR>"
"ὔ" p "<GR>>'u</GR>"
"ὕ" p "<GR><'u</GR>"
"ὖ" p "<GR>>=u</GR>"
"ὗ" p "<GR><=u</GR>"
"Ὑ" p "<GR><U</GR>"
"Ὓ" p "<GR><`U</GR>"
"Ὕ" p "<GR><'U</GR>"
"Ὗ" p "<GR><=U</GR>"

"ὠ" p "<GR>>w</GR>"
"ὡ" p "<GR><w</GR>"
"ὢ" p "<GR>>`w</GR>"
"ὣ" p "<GR><`w</GR>"
"ὤ" p "<GR>>'w</GR>"
"ὥ" p "<GR><'w</GR>"
"ὦ" p "<GR>>=w</GR>"
"ὧ" p "<GR><=w</GR>"
"Ὠ" p "<GR>>W</GR>"
"Ὡ" p "<GR><W</GR>"
"Ὢ" p "<GR>>`W</GR>"
"Ὣ" p "<GR><`W</GR>"
"Ὤ" p "<GR>>'W</GR>"
"Ὥ" p "<GR><'W</GR>"
"Ὦ" p "<GR>>=W</GR>"
"Ὧ" p "<GR><=W</GR>"

"ὰ" p "<GR>`a</GR>"
"ά" p "<GR>'a</GR>"
"ὲ" p "<GR>`e</GR>"
"έ" p "<GR>'e</GR>"
"ὴ" p "<GR>`h</GR>"
"ή" p "<GR>'h</GR>"
"ὶ" p "<GR>`i</GR>"
"ί" p "<GR>'i</GR>"
"ὸ" p "<GR>`o</GR>"
"ό" p "<GR>'o</GR>"
"ὺ" p "<GR>`u</GR>"
"ύ" p "<GR>'u</GR>"
"ὼ" p "<GR>`w</GR>"
"ώ" p "<GR>'w</GR>"

"ᾀ" p "<GR>>a|</GR>"
"ᾁ" p "<GR><a|</GR>"
"ᾂ" p "<GR>>`a|</GR>"
"ᾃ" p "<GR><`a|</GR>"
"ᾄ" p "<GR>>'a|</GR>"
"ᾅ" p "<GR><'a|</GR>"
"ᾇ" p "<GR>>=a|</GR>"
"ᾇ" p "<GR><=a|</GR>"
"ᾈ" p "<GR>>A|</GR>"
"ᾉ" p "<GR><A|</GR>"
"ᾊ" p "<GR>>`A|</GR>"
"ᾋ" p "<GR><`A|</GR>"
"ᾌ" p "<GR>>'A|</GR>"
"ᾍ" p "<GR><'A|</GR>"
"ᾎ" p "<GR>>=A|</GR>"
"ᾏ" p "<GR><=A|</GR>"

"ᾐ" p "<GR>>h|</GR>"
"ᾑ" p "<GR><h|</GR>"
"ᾒ" p "<GR>>`h|</GR>"
"ᾓ" p "<GR><`h|</GR>"
"ᾔ" p "<GR>>'h|</GR>"
"ᾕ" p "<GR><'h|</GR>"
"ᾖ" p "<GR>>=h|</GR>"
"ᾗ" p "<GR><=h|</GR>"
"ᾘ" p "<GR>>H|</GR>"
"ᾙ" p "<GR><H|</GR>"
"ᾚ" p "<GR>>`H|</GR>"
"ᾛ" p "<GR><`H|</GR>"
"ᾜ" p "<GR>>'H|</GR>"
"ᾝ" p "<GR><'H|</GR>"
"ᾞ" p "<GR>>=H|</GR>"
"ᾟ" p "<GR><=H|</GR>"

"ᾠ" p "<GR>>w|</GR>"
"ᾡ" p "<GR><w|</GR>"
"ᾢ" p "<GR>>`w|</GR>"
"ᾣ" p "<GR><`w|</GR>"
"ᾤ" p "<GR>>'w|</GR>"
"ᾥ" p "<GR><'w|</GR>"
"ᾦ" p "<GR>>=w|</GR>"
"ᾧ" p "<GR><=w|</GR>"
"ᾨ" p "<GR>>W|</GR>"
"ᾩ" p "<GR><W|</GR>"
"ᾪ" p "<GR>>`W|</GR>"
"ᾫ" p "<GR><`W|</GR>"
"ᾬ" p "<GR>>'W|</GR>"
"ᾭ" p "<GR><'W|</GR>"
"ᾮ" p "<GR>>=W|</GR>"
"ᾯ" p "<GR><=W|</GR>"

"ᾰ" p "<GR>)a</GR>"
"ᾱ" p "<GR>\\=a</GR>"
"ᾲ" p "<GR>`a|</GR>"
"ᾳ" p "<GR>a|</GR>"
"ᾴ" p "<GR>'a|</GR>"
"ᾶ" p "<GR>=a</GR>"
"ᾷ" p "<GR>=a|</GR>"
"Ᾰ" p "<GR>)A</GR>"
"Ᾱ" p "<GR>\\=A</GR>"
"Ὰ" p "<GR>`A</GR>"
"Ά" p "<GR>'A</GR>"
"ᾼ" p "<GR>A|</GR>"

"ῂ" p "<GR>`h|</GR>"
"ῃ" p "<GR>h|</GR>"
"ῄ" p "<GR>'h|</GR>"
"ῆ" p "<GR>=h</GR>"
"ῇ" p "<GR>=h|</GR>"
"Ὲ" p "<GR>`E</GR>"
"Έ" p "<GR>'E</GR>"
"Ὴ" p "<GR>`H</GR>"
"Ή" p "<GR>'H</GR>"
"ῌ" p "<GR>H|</GR>"

"ῐ" p "<GR>)i</GR>"
"ῑ" p "<GR>\\=i</GR>"
"ῒ" p "<GR>\"`i</GR>"
"ΐ" p "<GR>\"'i</GR>"
"ῖ" p "<GR>=i</GR>"
"ῗ" p "<GR>\"=i</GR>"
"Ῐ" p "<GR>)I</GR>"
"Ῑ" p "<GR>\\=I</GR>"
"Ὶ" p "<GR>`I</GR>"
"Ί" p "<GR>'I</GR>"

"ῠ" p "<GR>)u</GR>"
"ῡ" p "<GR>\\=u</GR>"
"ῢ" p "<GR>\"`u</GR>"
"ΰ" p "<GR>\"'u</GR>"
"ῤ" p "<GR>>r</GR>"
"ῥ" p "<GR><r</GR>"
"ῦ" p "<GR>=u</GR>"
"ῧ" p "<GR>\"=u</GR>"
"Ῠ" p "<GR>)U</GR>"
"Ῡ" p "<GR>\\=U</GR>"
"Ὺ" p "<GR>`U</GR>"
"Ύ" p "<GR>'U</GR>"
"Ῥ" p "<GR><R</GR>"

"ῲ" p "<GR>`w|</GR>"
"ῳ" p "<GR>w|</GR>"
"ῴ" p "<GR>'w|</GR>"
"ῶ" p "<GR>=w</GR>"
"ῷ" p "<GR>=w|</GR>"
"Ὸ" p "<GR>`O</GR>"
"Ό" p "<GR>'O</GR>"
"Ὼ" p "<GR>`W</GR>"
"Ώ" p "<GR>'W</GR>"
"ῼ" p "<GR>W|</GR>"


% modern accented letters (not to be used for classical Greek):

"Ά" p "<GR>'A</GR>"
"Έ" p "<GR>'E</GR>"
"Ή" p "<GR>'H</GR>"
"Ί" p "<GR>'I</GR>"
"Ό" p "<GR>'O</GR>"
"Ύ" p "<GR>'U</GR>"
"Ώ" p "<GR>'W</GR>"

"ά" p "<GR>'a</GR>"
"έ" p "<GR>'e</GR>"
"ή" p "<GR>'h</GR>"
"ί" p "<GR>'i</GR>"
"ό" p "<GR>'o</GR>"
"ύ" p "<GR>'u</GR>"
"ώ" p "<GR>'w</GR>"

"ΐ" p "<GR>\"'i</GR>"
"Ϊ" p "<GR>\"I</GR>"
"Ϋ" p "<GR>\"U</GR>"
"ΰ" p "<GR>\"'u</GR>"
"ϊ" p "<GR>\"i</GR>"
"ϋ" p "<GR>\"u</GR>"

@end
