image:https://github.com/jhellingman/tei2html/actions/workflows/test.yml/badge.svg[xspec tests,link=https://github.com/jhellingman/tei2html/actions/workflows/test.yml]
image:https://www.codefactor.io/repository/github/jhellingman/tei2html/badge[CodeFactor,link=https://www.codefactor.io/repository/github/jhellingman/tei2html]

== tei2html

`tei2html` is a collection of XSLT 3.0 style sheets to transform a document encoded in TEI to HTML. They have been specifically developed to generate a monolithic (single) HTML document for posting on https://www.gutenberg.org/[Project Gutenberg], but they can also generate ePub files from the same source with a similar look and feel. In line with the type of material Project Gutenberg deals with, these style sheets are designed to deal with encoded pre-existing works, rather than works created digitally from scratch.

The transformation supports the following elements as present in TEI:

* Plain Text and text styles
* Title Pages
* Tables
* Lists
* Tables of contents
* Poetry and Plays
* Footnotes
* Illustrations
* Cover images

Furthermore, the script can generate

* Tables of Contents.
* Lists of Corrections.
* Colophons
* Metadata as used in ePub

`tei2html` includes localisation support for English, Dutch, and to a lesser extent German, French, Spanish, Tagalog and Cebuano.

These scripts sometimes depend on a specific way of using `@rend` attributes and other TEI conventions. It should not be expected that an arbitrary TEI file renders well with those scripts, although they should render reasonable in any case.

If you need modifications, extensions of these scripts, or need to have other TEI/XML/XSLT related work done, please be in touch with me on how I can help.

== Directories

* `dtd`: some DTDs with a catalog file (mostly for use by `nsgml`)
* `locale`: localization information.
* `modules`: most of the XSLT code itself.
* `pptools`: post-processing tools that are mostly useful for preparing TEI-files from the output of Project Gutenberg Distributed Proofreaders. 
* `samples`: a few sample TEI files of books posted to Project Gutenberg. I am currently adding my TEI source files to GitHub: see https://github.com/GutenbergSource[GutenbergSource] for many more examples.
* `sandbox`: experimental code, better ignored if you don't want to play around.
* `schemas`: schema definitions for some supplementary XML formats.
* `schematron`: a schematron file to validate several aspects of TEI files.
* `style`: CSS stylesheets, used by the generated HTML and ePub results.
* `test`: a test TEI file, complete with the generated output in XML, HTML and ePub format. This is used to verify the correct transformation. It contains various examples, and serves as a regression test when refactoring the XSLT transforms.
* `tools`: perl scripts used to apply the transforms; also includes perl scripts that can be used while preparing TEI files.
* `Wiki`: wiki-pages that give some instructions and background documentation. Also available as a http://jhellingman.github.io/tei2html/Index.html[single HTML file].
* `xspec`: xspec tests that cover various (but not yet all) aspects of the XSLT transforms.

== External Links

* https://tei-c.org/Tools/[TEI tools]
* https://github.com/TEIC/Stylesheets[Another take at converting TEI to HTML]
* https://wiki.tei-c.org/index.php/Tei-xsl[Another link to TEI converters]
* https://teigarage.tei-c.org/[TEIGarage, tools to convert TEI files]
