= Auxiliary Tools

Besides the main XSLT scripts, `tei2html` includes Perl scripts for various tasks. Many of these are quick hacks to get things done.


== The main tools

=== tei2html.pl

The Perl script `tei2html.pl` is the main 'glue' script. This will run the various commands to actually apply the `tei2html` XSLT stylesheets.

Syntax: `perl.pl -S tei2html.pl [options] filename`

For an overview of options, run `perl.pl -S tei2html.pl --help`

=== ucwords.pl

The Perl script `ucwords.pl` is used to list word-frequencies in an XML file. This script will recognize the `@lang` tag, and write a word-frequency list per language encountered. Words in the output will be color-coded, based on frequency and appearance in a spell-check dictionary.

Syntax: `perl -S ucwords.pl filename`


== Tools to generate plain text files

=== extractNotes.pl

`extractNotes.pl` extracts TEI tagged notes from a text file.

Usage:

    perl extractNotes.pl [-h] <filename>

Options:

    -h	perpare for HTML output.

This produces two output files:

    <filename>.out	The original text without the notes
    <filename>.not	The notes

If the `-h` option is used, hyperlinks between the two files are inserted.
Otherwise, the notes are indicated with a sequence number in square
brackets.

=== tei2txt.pl

`tei2txt.pl` converts a TEI file to plain vanilla ASCII.

Usage:

    perl tei2txt.pl <filename>

Notes:

1. This script assumes `extractNotes.pl` has been run before.
2. Accented and special letters are converted to their nearest ASCII equivalents.


=== tei2txt.bat

`tei2txt.bat` converts a TEI file to plain vanilla ASCII.

This batch file first runs `extractNotes.pl`, concatenates the two resulting files, and then runs `tei2txt.pl` on the resulting file. The result is a single ASCII file.


== Tools for post-processing PGDP output

=== fixpb.pl

The Perl script `fixpb.pl` fixes page numbers, as recorded in the `@n` attribute in `&lt;pb&gt;` elements. This will also set the `@id` attribute to `pb#`, where `#` is the current page number. Page-numbers will be changed after the page indicated, with an offset indicated. To fix mismatched page-numbers, always start with the first mismatch, and run the script as many times as needed (this typically occurs if the original source had unnumbered pages with illustrations.)

For an overview of options, run `perl.pl -S fixpb.pl --help`

=== catpars.pl

The Perl script `catpars.pl` unwraps paragraphs, such that they appear on one line. Handle with care, as it might unwrap entire tables or lists if it deems them part of a paragraph.

=== quotes.pl

The Perl script `quotes.pl` replaces ASCII single and double-quotes with curly quotes. May need some manual verification and correction where quotes and tags interfere with the simple algorithm used.

Issues:

* Open quotes before SGML tags and non-letters may go wrong (they become the default: a close quote).
* Manually check for ASCII single-quotes, and apply the correct one. Use `tei2html.pl` with the `-v` option to find cases where quotes are still not balanced.

=== pgpp.pl

The Perl script `pgpp.pl` should be run initially on the output from PG Distributed Proofreaders, when converting that to TEI (the actual conversion is a manual process, as the resulting output is still very far removed from a syntactically correct TEI file).


== Tools for preparing texts for PGDP

=== pgprepare.pl

The Perl script `pgprepare.pl` converts a set of text files in a directory to UTF-8, normalizes spacing, and removes some unwanted characters. It assumes its input is in the latin-1 character set, so don't run it twice on the same set of files.
