= Checking a TEI file

`checks.xsl` is an XSLT stylesheet to check various TEI conventions and textual issues. I am in the process of converting most of these tests to schematron, but for the time being it will be the primary way to check for correctness of TEI files being processed by `tei2html`.

== Metadata

Verify metadata is present and correct.

== Rendering

Verify valid rendering attributes are used

* valid CSS-based rendition ladders
* valid `tei2html` extensions.

== Types

Verify types for elements are valid according to the conventions.

== Numbering

Verify whether numbered items are in sequence.

* page-breaks `&lt;pb&gt;`
* divisions `&lt;div#&gt;`

== Spacing and Punctuation

Verify punctuation marks are properly spaced.

== Quotation Marks

Verify whether quotation marks are applied correctly.

Quotation marks need to be nested correctly, and for each
opening mark, there should be a corresponding closing mark.

This is slightly complicated by several facts:

* different types of usage
** US: outer double, inner single quotation marks
** UK: outer single, inner double quotation marks
* different conventions for languages and countries.
* usage around other punctuation might vary.
* non-closed marks are to be re-opened in next paragraph.

To make this test work best, you should configure the exact type of quotation marks used in the `tei2html.config` file with your text, using the `text.quotes` setting.
