= Those Pesky Page-Breaks

Printed books have pages, and thus page-breaks every couple of hundred words or so. Electronic files do not have this concept, but since pages and page numbers have traditionally been used to refer to passages in books, they can be captured in `&lt;pb&gt;` elements, which, for good reason, can appear almost anywhere in a TEI document. Here is where the trouble starts.

Reference:

* TEI P5 Documentation https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-pb.html[pb]

== Encoding

When a page-break occurs between two divisions, it can be encoded in various was, _e.g._, before the closing tag:

[source,xml]
----
<pb n="123"/>
</div1>
<div1>
----

Between the closing and opening tag:

[source,xml]
----
</div1>
<pb n="123"/>
<div1>
----

After the opening tag:

[source,xml]
----
</div1>
<div1>
<pb n="123"/>
----

Various guidelines for TEI propose different (conflicting) conventions for each option. The `tei2html` scripts all assume the first option (before the closing tag) This way, the generated tables of content, etc., refer to page-number that is current when the `&lt;div1&gt;` tag occurs.

It should be very well possible to write a small XSLT script to normalize this usage, avoiding complications in the other XSLT scripts.

== Page Images

See link:FacsimileSupport.adoc[facsimile support]

== Cross-References

As mentioned, cross-references in printed books often reference to page numbers. The easiest way to encode this is to do something like this:

----
For details <ref target="pb123">see page 123</ref>.
----

However, there are several problems with this approach:

. This reference refers to a `&lt;pb id=&quot;pb123&quot; n=&quot;123&quot;/&gt;` somewhere in text. Now, of course, the reference is almost never to the page-break itself, but always to some content that appears on that page (a picture, a paragraph or phrase), but actually identifying and linking to the content referred to can be a time-consuming task, so is often postponed (think, for example, about a pre-existing index). So we often have texts that just link like this.
. The reference contains more than just the page number. This makes it harder to replace the page number with the actual page number in paged output, if such is generated.
. The reference does not make clear that it is indeed to a page number (which could hint the rendering process to replace it when rendering on paged media).

For these reasons, `tei2html` specifies that references to page-numbers are tagged as:

----
For details see page <ref target="pb123" type="pageref">123</ref>.
----

That is, directly surrounding the page number, and the additional `@type` attribute set to pageref. This indicates to the rendering application that the content of the `&lt;ref&gt;` element needs to be replaced with the actual page number on which the details appear.

To prevent that the details do not appear on the indicated page, but on a previous or next page, you should replace the target with the non-`&lt;pb&gt;` element the details are really in (most likely a paragraph).

When creating new paged output, we will have to deal with yet another set of issues:

First, exact values for cross-references can only be established when final pagination is known. In some cases, this may result in changes in the page layout inducing changes in the page numbers itself ("see page 100" is wider than "see page 99"). Most current layout tools can deal with this type of issues reasonably, although in some extreme cases this still pops up.

Second, when generating an index, you want to avoid things like

  common entry, 12, 12, 12, 23, 24, 25, 45.

but summarize them as

  common entry 12, 23-25, 45.

which is not supported by most current index generating tools, and is pretty hard to do as well. (`tei2html` does this when referring to pre-existing page-numbers, but this is not very useful for paged output.)
