== The TEI Header

The TEI header (`&lt;teiHeader&gt;`) contains information about the text and the sources it is derived from. This metadata is grouped in various sections, in which it is often possible to distinguish information related to the electronic file from that related to the original source.

`tei2html` uses the metadata in the TEI header to construct the meta-data in the target formats, as well as the optional colophon. It is important to correctly specify the metadata in the TEI header.

Preparing a TEI header is less work than it might seem, as you can normally work from a template, prepared with the most common elements already in place.

The TEI header contains four main sections:

[source,xml]
----
    <teiHeader>
        <fileDesc>...</fileDesc>
        <encodingDesc>...</encodingDesc>
        <profileDesc>...</profileDesc>
        <revisionDesc>...</revisionDesc>
    </teiHeader>
----

=== The File Description

The first element of the TEI header is the file description, `&lt;fileDesc&gt;`. This contains the most important meta-data in three main elements, the `&lt;titleStmt&gt;`, `&lt;publicationStmt&gt;`, and `&lt;sourceDesc&gt;`. Our template looks like this.

[source,xml]
----
    <fileDesc>
        <titleStmt>
            <title>TITLE</title>
            <author>AUTHOR</author>
        </titleStmt>
        <publicationStmt>
            <publisher>Project Gutenberg</publisher>
            <pubPlace>Urbana, Illinois, USA.</pubPlace>
            <idno type="PGNum">12345</idno>
            <date>2010-01-31</date>
            <availability>
                <p>Some statements on the availability and copyright status of the work.</p>
            </availability>
        </publicationStmt>
        <sourceDesc>
        <bibl>
            <author>AUTHOR</author>
            <title>TITLE</title>
            <date>YEAR</date>
        </bibl>
        </sourceDesc>
    </fileDesc>
----

You might notice that the TEI header contains the title and author information twice. This is intentional, as one refers to the title of the file, and one to the title of the source. For the title given in the `&lt;titleStmt&gt;`, some TEI recommendations suggest appending "an electronic transcription" to the original title. I think that is unnecessary, and will use the original title as given on the title page, or perhaps normalized in some fashion. For personal names, I always give them in the natural order, that is, without a comma, and optionally I will supply the vital dates in parentheses, for example, `&lt;author&gt;John Doe (1833-1901)&lt;/author&gt;`. You may add other elements allowed by TEI in this statement if needed.

In the publication statement, you can give some information on the publisher and the availability of the book. For typical Project Gutenberg publications, the information in the template is fine.

The following specific values can be used in the `&lt;publicationStmt&gt;` element to register the various ways the text is known at Project Gutenberg and elsewhere.

[cols="<,<"]
|===
|*ID type* |*Used for* 

|`&lt;idno type=PGNum&gt;12345&lt;/idno&gt;` |The Project Gutenberg eBook number. 
|`&lt;idno type=PGDPProjectID&gt;project1234&lt;/idno&gt;` |The PGDP project number(s). 
|`&lt;idno type=PGClearance&gt;1234name&lt;/idno&gt;` |The PG Clearance number. 
|`&lt;idno type=OCLC&gt;&lt;/idno&gt;` |OCLC catalog number (worldcat). 
|`&lt;idno type=OLN&gt;&lt;/idno&gt;` |Open Library catalog number. 
|`&lt;idno type=LCCN&gt;&lt;/idno&gt;` |Library of Congress Call Number. 
|`&lt;idno type=ISBN&gt;&lt;/idno&gt;` |The ISBN. Since ISBNs refer to specific manifestations of a work, this number typically refers to the ISBN of the source digitized. ISBNs have been in use since 1972, so it is unlikely many Project Gutenberg books have such a number. (you are not supposed to use the ISBN of the source here!)
|===

The `&lt;availability&gt;` element should include a short reference to the copyright status of the work. For most texts in Project Gutenberg, the following phrase will be appropriate: _Not copyrighted in the United States. If you live elsewhere please check the laws of your country before downloading this ebook._

In the `&lt;sourceDesc&gt;`, the title and author information appears again. This time, you should use the exact title and author names as given on the title page of the original work used to prepare your Project Gutenberg text. If the title on the spine or cover of the book differs, this may be noted, but the title page is leading.

==== Extensions to TEI

The `@nfc` attribute on `&lt;title&gt;` elements is used to indicate the number of non-filing characters, used when sorting a title. Counted should be all characters up to the character on which the title should be sorted, including spaces.

[source,xml]
----
    <title nfc="4">The Return of the King</title>
    <title nfc="3">An Introduction to Mathematics</title>
----

The `@key` attribute on `&lt;author&gt;` and related elements is used to supply a sort key for a name. Typically, such sort keys would drop accents, such that they will sort in the expected place in lists.

I also use the `@ref` key to provide a link to the viaf.org authority file.

[source,xml]
----
    <author key="Rijn, Rembrandt, Harmenszoon van" ref="http://viaf.org/viaf/64013650">Rembrandt van Rhijn (1606-1669)</author>
    <author key="MacKenzee, John">John McKenzee</author>
    <author key="Hotel, Desire l'">Desiré l'Hôtel</author>
----
