% Classical Greek in PGDP notation to my transcription.

@patterns 0 % normal mode

"[GR:"      1 "<GR>"
"[GR: "     1 "<GR>"
"[Greek:"   1 "<GR>"
"[Greek: "  1 "<GR>"


@patterns 2 % skip proofer comments in Greek

"]"         1 "]<GR>"

@patterns 1 % Greek transcription mode

"[*"        2 "</GR>[*"

"]"         0 "</GR>"
"s]"        0 "c</GR>"
"\n\n"      0 "</GR>\n\n"
"<br>"      p "</GR><br><GR>"

"'"         p "&apos;"

"a"         p "a"

"A"         p "A"
"a|"        p "a|"
"A|"        p "A|"
"a(|"       p "<a|"
"A(|"       p "<A|"
"a)|"       p ">a|"
"A)|"       p ">A|"
"a/|"       p "'a|"
"A/|"       p "'A|"
"a\\|"      p "`a|"
"A\\|"      p "`A|"
"a=|"       p "=a|"
"A=|"       p "=A|"
"a(/|"      p "<'a|"
"A(/|"      p "<'A|"
"a)/|"      p ">'a|"
"A)/|"      p ">'A|"
"a(\\|"     p "<`a|"
"A(\\|"     p "<`A|"
"a)\\|"     p ">`a|"
"A)\\|"     p ">`A|"
"a(=|"      p "<=a|"
"A(=|"      p "<=A|"
"a)=|"      p ">=a|"
"A)=|"      p ">=A|"

"a|("       p "<a|"
"A|("       p "<A|"
"a|)"       p ">a|"
"A|)"       p ">A|"
"a|/"       p "'a|"
"A|/"       p "'A|"
"a|\\"      p "`a|"
"A|\\"      p "`A|"
"a|="       p "=a|"
"A|="       p "=A|"
"a|(/"      p "<'a|"
"A|(/"      p "<'A|"
"a|)/"      p ">'a|"
"A|)/"      p ">'A|"
"a|(\\"     p "<`a|"
"A|(\\"     p "<`A|"
"a|)\\"     p ">`a|"
"A|)\\"     p ">`A|"
"a|(="      p "<=a|"
"A|(="      p "<=A|"
"a|)="      p ">=a|"
"A|)="      p ">=A|"

"a("        p "<a"
"A("        p "<A"
"a)"        p ">a"
"A)"        p ">A"
"a\\"       p "`a"
"A\\"       p "`A"
"a/"        p "'a"
"A/"        p "'A"
"a="        p "=a"
"A="        p "=A"
"a(/"       p "<'a"
"A(/"       p "<'A"
"a)/"       p ">'a"
"A)/"       p ">'A"
"a(\\"      p "<`a"
"A(\\"      p "<`A"
"a)\\"      p ">`a"
"A)\\"      p ">`A"
"a(="       p "<=a"
"A(="       p "<=A"
"a)="       p ">=a"
"A)="       p ">=A"

"b"         p "b"
"B"         p "B"

"g"         p "g"
"G"         p "G"

"d"         p "d"
"D"         p "D"

"e"         p "e"
"E"         p "E"
"e("        p "<e"
"E("        p "<E"
"e)"        p ">e"
"E)"        p ">E"
"e\\"       p "`e"
"E\\"       p "`E"
"e/"        p "'e"
"E/"        p "'E"
"e="        p "=e"
"E="        p "=E"
"e(/"       p "<'e"
"E(/"       p "<'E"
"e)/"       p ">'e"
"E)/"       p ">'E"
"e(\\"      p "<`e"
"E(\\"      p "<`E"
"e)\\"      p ">`e"
"E)\\"      p ">`E"
"e(="       p "<=e"
"E(="       p "<=E"
"e)="       p ">=e"
"E)="       p ">=E"

"z"         p "z"
"Z"         p "Z"

"ê"         p "h"
"Ê"         p "H"

"ê|"        p "h|"
"Ê|"        p "H|"
"ê(|"       p "<h|"
"Ê(|"       p "<H|"
"ê)|"       p ">h|"
"Ê)|"       p ">H|"
"ê/|"       p "'h|"
"Ê/|"       p "'H|"
"ê\\|"      p "`h|"
"Ê\\|"      p "`H|"
"ê=|"       p "=h|"
"Ê=|"       p "=H|"
"ê(/|"      p "<'h|"
"Ê(/|"      p "<'H|"
"ê)/|"      p ">'h|"
"Ê)/|"      p ">'H|"
"ê(\\|"     p "<`h|"
"Ê(\\|"     p "<`H|"
"ê)\\|"     p ">`h|"
"Ê)\\|"     p ">`H|"
"ê(=|"      p "<=h|"
"Ê(=|"      p "<=H|"
"ê)=|"      p ">=h|"
"Ê)=|"      p ">=H|"

"ê|("       p "<h|"
"Ê|("       p "<H|"
"ê|)"       p ">h|"
"Ê|)"       p ">H|"
"ê|/"       p "'h|"
"Ê|/"       p "'H|"
"ê|\\"      p "`h|"
"Ê|\\"      p "`H|"
"ê|="       p "=h|"
"Ê|="       p "=H|"
"ê|(/"      p "<'h|"
"Ê|(/"      p "<'H|"
"ê|)/"      p ">'h|"
"Ê|)/"      p ">'H|"
"ê|(\\"     p "<`h|"
"Ê|(\\"     p "<`H|"
"ê|)\\"     p ">`h|"
"Ê|)\\"     p ">`H|"
"ê|(="      p "<=h|"
"Ê|(="      p "<=H|"
"ê|)="      p ">=h|"
"Ê|)="      p ">=H|"

"ê("        p "<h"
"Ê("        p "<H"
"ê)"        p ">h"
"Ê)"        p ">H"
"ê\\"       p "`h"
"Ê\\"       p "`H"
"ê/"        p "'h"
"Ê/"        p "'H"
"ê="        p "=h"
"Ê="        p "=H"
"ê(/"       p "<'h"
"Ê(/"       p "<'H"
"ê)/"       p ">'h"
"Ê)/"       p ">'H"
"ê(\\"      p "<`h"
"Ê(\\"      p "<`H"
"ê)\\"      p ">`h"
"Ê)\\"      p ">`H"
"ê(="       p "<=h"
"Ê(="       p "<=H"
"ê)="       p ">=h"
"Ê)="       p ">=H"

"th"        p "j"
"Th"        p "J"
"TH"        p "J"

"i"         p "i"
"I"         p "I"
"i("        p "<i"
"I("        p "<I"
"i)"        p ">i"
"I)"        p ">I"
"i\\"       p "`i"
"I\\"       p "`I"
"i/"        p "'i"
"I/"        p "'I"
"i="        p "=i"
"I="        p "=I"
"i(/"       p "<'i"
"I(/"       p "<'I"
"i)/"       p ">'i"
"I)/"       p ">'I"
"i(\\"      p "<`i"
"I(\\"      p "<`I"
"i)\\"      p ">`i"
"I)\\"      p ">`I"
"i(="       p "<=i"
"I(="       p "<=I"
"i)="       p ">=i"
"I)="       p ">=I"

"i+"        p "\"i"
"I+"        p "\"I"
"i+\\"      p "`\"i"
"i+/"       p "'\"i"
"i+="       p "=\"i"

"k"         p "k"
"K"         p "K"

"l"         p "l"
"L"         p "L"

"m"         p "m"
"M"         p "M"

"n"         p "n"
"N"         p "N"

"x"         p "x"
"X"         p "X"

"o"         p "o"
"O"         p "O"
"o("        p "<o"
"O("        p "<O"
"o)"        p ">o"
"O)"        p ">O"
"o\\"       p "`o"
"O\\"       p "`O"
"o/"        p "'o"
"O/"        p "'O"
"o="        p "=o"
"O="        p "=O"
"o(/"       p "<'o"
"O(/"       p "<'O"
"o)/"       p ">'o"
"O)/"       p ">'O"
"o(\\"      p "<`o"
"O(\\"      p "<`O"
"o)\\"      p ">`o"
"O)\\"      p ">`O"
"o(="       p "<=o"
"O(="       p "<=O"
"o)="       p ">=o"
"O)="       p ">=O"

"p"         p "p"
"P"         p "P"

"r"         p "r"
"R"         p "R"
"r("        p "<r"
"R("        p "<R"
"r)"        p ">r"
"R)"        p ">R"

"s"         p "s"
"S"         p "S"

"s "        p "c "
"s."        p "c."
"s,"        p "c,"

"t"         p "t"
"T"         p "T"

"u"         p "u"
"U"         p "U"
"u("        p "<u"
"U("        p "<U"
"u)"        p ">u"
"U)"        p ">U"
"u\\"       p "`u"
"U\\"       p "`U"
"u/"        p "'u"
"U/"        p "'U"
"u="        p "=u"
"U="        p "=U"
"u(/"       p "<'u"
"U(/"       p "<'U"
"u)/"       p ">'u"
"U)/"       p ">'U"
"u(\\"      p "<`u"
"U(\\"      p "<`U"
"u)\\"      p ">`u"
"U)\\"      p ">`U"
"u(="       p "<=u"
"U(="       p "<=U"
"u)="       p ">=u"
"U)="       p ">=U"

"u+"        p "\"u"
"U+"        p "\"U"
"u+\\"      p "`\"u"
"u+/"       p "'\"u"
"u+="       p "=\"u"

"y"         p "u"
"Y"         p "U"
"y("        p "<u"
"Y("        p "<U"
"y)"        p ">u"
"Y)"        p ">U"
"y\\"       p "`u"
"Y\\"       p "`U"
"y/"        p "'u"
"Y/"        p "'U"
"y="        p "=u"
"Y="        p "=U"
"y(/"       p "<'u"
"Y(/"       p "<'U"
"y)/"       p ">'u"
"Y)/"       p ">'U"
"y(\\"      p "<`u"
"Y(\\"      p "<`U"
"y)\\"      p ">`u"
"Y)\\"      p ">`U"
"y(="       p "<=u"
"Y(="       p "<=U"
"y)="       p ">=u"
"Y)="       p ">=U"

"y+"        p "\"u"
"Y+"        p "\"U"
"y+\\"      p "`\"u"
"y+/"       p "'\"u"
"y+="       p "=\"u"

"f"         p "f"
"F"         p "F"
"ph"        p "f"
"Ph"        p "F"
"PH"        p "F"

"ch"        p "q"
"Ch"        p "Q"
"CH"        p "Q"

"ps"        p "y"
"Ps"        p "Y"
"PS"        p "Y"

"ô"         p "w"
"Ô"         p "W"

"ô|"        p "w|"
"Ô|"        p "W|"
"ô(|"       p "<w|"
"Ô(|"       p "<W|"
"ô)|"       p ">w|"
"Ô)|"       p ">W|"
"ô/|"       p "'w|"
"Ô/|"       p "'W|"
"ô\\|"      p "`w|"
"Ô\\|"      p "`W|"
"ô=|"       p "=w|"
"Ô=|"       p "=W|"
"ô(/|"      p "<'w|"
"Ô(/|"      p "<'W|"
"ô)/|"      p ">'w|"
"Ô)/|"      p ">'W|"
"ô(\\|"     p "<`w|"
"Ô(\\|"     p "<`W|"
"ô)\\|"     p ">`w|"
"Ô)\\|"     p ">`W|"
"ô(=|"      p "<=w|"
"Ô(=|"      p "<=W|"
"ô)=|"      p ">=w|"
"Ô)=|"      p ">=W|"

"ô|("       p "<w|"
"Ô|("       p "<W|"
"ô|)"       p ">w|"
"Ô|)"       p ">W|"
"ô|/"       p "'w|"
"Ô|/"       p "'W|"
"ô|\\"      p "`w|"
"Ô|\\"      p "`W|"
"ô|="       p "=w|"
"Ô|="       p "=W|"
"ô|(/"      p "<'w|"
"Ô|(/"      p "<'W|"
"ô|)/"      p ">'w|"
"Ô|)/"      p ">'W|"
"ô|(\\"     p "<`w|"
"Ô|(\\"     p "<`W|"
"ô|)\\"     p ">`w|"
"Ô|)\\"     p ">`W|"
"ô|(="      p "<=w|"
"Ô|(="      p "<=W|"
"ô|)="      p ">=w|"
"Ô|)="      p ">=W|"

"ô("        p "<w"
"Ô("        p "<W"
"ô)"        p ">w"
"Ô)"        p ">W"
"ô\\"       p "`w"
"Ô\\"       p "`W"
"ô/"        p "'w"
"Ô/"        p "'W"
"ô="        p "=w"
"Ô="        p "=W"
"ô(/"       p "<'w"
"Ô(/"       p "<'W"
"ô)/"       p ">'w"
"Ô)/"       p ">'W"
"ô(\\"      p "<`w"
"Ô(\\"      p "<`W"
"ô)\\"      p ">`w"
"Ô)\\"      p ">`W"
"ô(="       p "<=w"
"Ô(="       p "<=W"
"ô)="       p ">=w"
"Ô)="       p ">=W"

%% Vowels with macrons (TODO: combinations of macron with other accents, [=a])/, [=i]/, etc. Use Unicode combining accents.)
%% sometimes mistakes for the "circumflex"

"[=a]"      p "\\=a"
"[=A]"      p "\\=A"
"[=a]/"     p "\\=a&#x301;"
"[=A]/"     p "\\=A&#x301;"
"[=a])/"    p "\\=a&#x313;&#x301;"
"[=A])/"    p "\\=A&#x313;&#x301;"

"[=e]"      p "\\=e"
"[=E]"      p "\\=E"

"[=i]"      p "\\=i"
"[=I]"      p "\\=I"
"[=i]/"     p "\\=i&#x301;"
"[=I]/"     p "\\=I&#x301;"

"[=ê]"      p "\\=h"
"[=Ê]"      p "\\=H"

"[=o]"      p "\\=o"
"[=O]"      p "\\=O"

"[=u]"      p "\\=u"
"[=U]"      p "\\=U"
"[=y]"      p "\\=u"
"[=Y]"      p "\\=U"

"[=ô]"      p "\\=w"
"[=Ô]"      p "\\=W"

%% additional letters

"v"         p "&digamma;"
"[f]"       p "&digamma;"
"[j]"       p "&jgr;";
"[(]"       p "&lpar;";
"[)]"       p "&rpar;";

"[^*]"      p "[^*]";   %% FRANCK: raised asterisk.


%% warn for illegal characters

"c"         p "</GR><span class=error>c</span><GR>"
"C"         p "</GR><span class=error>C</span><GR>"
"w"         p "</GR><span class=error>w</span><GR>"
"W"         p "</GR><span class=error>W</span><GR>"
"V"         p "</GR><span class=error>V</span><GR>"
"v"         p "</GR><span class=error>v</span><GR>"
"j"         p "</GR><span class=error>j</span><GR>"
"J"         p "</GR><span class=error>J</span><GR>"
"["         p "</GR><span class=error>[</span><GR>"

"("         p "</GR><span class=error>(</span><GR>"
")"         p "</GR><span class=error>)</span><GR>"
"/"         p "</GR><span class=error>/</span><GR>"
"\\"        p "</GR><span class=error>\\</span><GR>"
"+"         p "</GR><span class=error>+</span><GR>"
"="         p "</GR><span class=error>=</span><GR>"
"\""        p "</GR><span class=error>\"</span><GR>"


@end
