
@patterns 0

"<foreign xml:lang=\"grc\">"    1 "<foreign xml:lang=\"grc\">"


@patterns 1

"</foreign>"    0 "</foreign>"

% No marks
"a"     p     "&#x03b1;"
"b"     p     "&#x03b2;"
"g"     p     "&#x03b3;"
"d"     p     "&#x03b4;"
"e"     p     "&#x03b5;"
"z"     p     "&#x03b6;"
"h"     p     "&#x03b7;"
"q"     p     "&#x03b8;"
"i"     p     "&#x03b9;"
"k"     p     "&#x03ba;"
"l"     p     "&#x03bb;"
"m"     p     "&#x03bc;"
"n"     p     "&#x03bd;"
"c"     p     "&#x03be;"
"o"     p     "&#x03bf;"
"p"     p     "&#x03c0;"
"r"     p     "&#x03c1;"
"s"     p     "&#x03c3;"
"s1"    p     "&#x03c3;"
"s2"    p     "&#x03c2;"
"s3"    p     "&#x03f2;"
"t"     p     "&#x03c4;"
"u"     p     "&#x03c5;"
"f"     p     "&#x03c6;"
"x"     p     "&#x03c7;"
"y"     p     "&#x03c8;"
"w"     p     "&#x03c9;"
"*a"    p     "&#x0391;"
"*b"    p     "&#x0392;"
"*g"    p     "&#x0393;"
"*d"    p     "&#x0394;"
"*e"    p     "&#x0395;"
"*z"    p     "&#x0396;"
"*h"    p     "&#x0397;"
"*q"    p     "&#x0398;"
"*i"    p     "&#x0399;"
"*k"    p     "&#x039a;"
"*l"    p     "&#x039b;"
"*m"    p     "&#x039c;"
"*n"    p     "&#x039d;"
"*c"    p     "&#x039e;"
"*o"    p     "&#x039f;"
"*p"    p     "&#x03a0;"
"*r"    p     "&#x03a1;"
"*s"    p     "&#x03a3;"
"*s3"   p     "&#x03f9;"
"*t"    p     "&#x03a4;"
"*u"    p     "&#x03a5;"
"*f"    p     "&#x03a6;"
"*x"    p     "&#x03a7;"
"*y"    p     "&#x03a8;"
"*w"    p     "&#x03a9;"

% Smooth breathing
"a)" p     "&#x1f00;"
"e)" p     "&#x1f10;"
"h)" p     "&#x1f20;"
"i)" p     "&#x1f30;"
"o)" p     "&#x1f40;"
"u)" p     "&#x1f50;"
"w)" p     "&#x1f60;"
"r)" p     "&#x1fe4;"
"*)a" p    "&#x1f08;"
"*)e" p    "&#x1f18;"
"*)h" p    "&#x1f28;"
"*)i" p    "&#x1f38;"
"*)o" p    "&#x1f48;"
"*)w" p    "&#x1f68;"

% Rough breathing
"a(" p     "&#x1f01;"
"e(" p     "&#x1f11;"
"h(" p     "&#x1f21;"
"i(" p     "&#x1f31;"
"o(" p     "&#x1f41;"
"u(" p     "&#x1f51;"
"w(" p     "&#x1f61;"
"r(" p     "&#x1fe5;"
"*(a" p    "&#x1f09;"
"*(e" p    "&#x1f19;"
"*(h" p    "&#x1f29;"
"*(i" p    "&#x1f39;"
"*(o" p    "&#x1f49;"
"*(u" p    "&#x1f59;"
"*(w" p    "&#x1f69;"
"*(r" p    "&#x1fec;"

% Acute accent and grave accent
"a\\" p    "&#x1f70;"
"a/" p     "&#x1f71;"
"e\\" p    "&#x1f72;"
"e/" p     "&#x1f73;"
"h\\" p    "&#x1f74;"
"h/" p     "&#x1f75;"
"i\\" p    "&#x1f76;"
"i/" p     "&#x1f77;"
"o\\" p    "&#x1f78;"
"o/" p     "&#x1f79;"
"u\\" p    "&#x1f7a;"
"u/" p     "&#x1f7b;"
"w\\" p    "&#x1f7c;"
"w/" p     "&#x1f7d;"
"*\\a" p   "&#x1fba;"
"*/a" p    "&#x1fbb;"
"*\\e" p   "&#x1fce;"
"*/e" p    "&#x1fc9;"
"*\\h" p   "&#x1fca;"
"*/h" p    "&#x1fcb;"
"*\\i" p   "&#x1fda;"
"*/i" p    "&#x1fdb;"
"*\\o" p   "&#x1ff8;"
"*/o" p    "&#x1ff9;"
"*\\u" p   "&#x1fea;"
"*/u" p    "&#x1feb;"
"*\\w" p   "&#x1ffa;"
"*/w" p    "&#x1ffb;"

% Smooth breathing and acute accent
"a)/" p    "&#x1f04;"
"e)/" p    "&#x1f14;"
"h)/" p    "&#x1f24;"
"i)/" p    "&#x1f34;"
"o)/" p    "&#x1f44;"
"u)/" p    "&#x1f54;"
"w)/" p    "&#x1f64;"
"*)/a" p   "&#x1f0c;"
"*)/e" p   "&#x1f1c;"
"*)/h" p   "&#x1f2c;"
"*)/i" p   "&#x1f3c;"
"*)/o" p   "&#x1f4c;"
"*)/u" p   "&#x1f5c;"
"*)/w" p   "&#x1f6c;"

% Smooth breathing and grave accent
"a)\\" p   "&#x1f02;"
"e)\\" p   "&#x1f12;"
"h)\\" p   "&#x1f22;"
"i)\\" p   "&#x1f32;"
"o)\\" p   "&#x1f42;"
"u)\\" p   "&#x1f52;"
"w)\\" p   "&#x1f62;"
"*)\\a" p  "&#x1f0a;"
"*)\\e" p  "&#x1f1a;"
"*)\\h" p  "&#x1f2a;"
"*)\\i" p  "&#x1f3a;"
"*)\\o" p  "&#x1f4a;"
"*)\\u" p  "&#x1f5a;"
"*)\\w" p  "&#x1f6a;"

% Rough breathing and acute accent
"a(/" p    "&#x1f05;"
"e(/" p    "&#x1f15;"
"h(/" p    "&#x1f25;"
"i(/" p    "&#x1f35;"
"o(/" p    "&#x1f45;"
"u(/" p    "&#x1f55;"
"w(/" p    "&#x1f65;"
"*(/a" p   "&#x1f0d;"
"*(/e" p   "&#x1f1d;"
"*(/h" p   "&#x1f2d;"
"*(/i" p   "&#x1f3d;"
"*(/o" p   "&#x1f4d;"
"*(/u" p   "&#x1f5d;"
"*(/w" p   "&#x1f6d;"

% Rough breathing and grave accent
"a(\\" p   "&#x1f03;"
"e(\\" p   "&#x1f13;"
"h(\\" p   "&#x1f23;"
"i(\\" p   "&#x1f33;"
"o(\\" p   "&#x1f43;"
"u(\\" p   "&#x1f53;"
"w(\\" p   "&#x1f63;"
"*(\\a" p  "&#x1f0b;"
"*(\\e" p  "&#x1f1b;"
"*(\\h" p  "&#x1f2b;"
"*(\\i" p  "&#x1f3b;"
"*(\\o" p  "&#x1f4b;"
"*(\\u" p  "&#x1f5b;"
"*(\\w" p  "&#x1f6b;"

% Perispomeni
"a=" p    "&#x1fb6;"
"h=" p    "&#x1fc6;"
"i=" p    "&#x1fd6;"
"u=" p    "&#x1fe6;"
"w=" p    "&#x1ff6;"

% Smooth breathing and perispomeni
"a)=" p   "&#x1f06;"
"h)=" p   "&#x1f26;"
"i)=" p   "&#x1f36;"
"u)=" p   "&#x1f56;"
"w)=" p   "&#x1f66;"
"*)=a" p  "&#x1f0e;"
"*)=h" p  "&#x1f2e;"
"*)=i" p  "&#x1f3e;"
"*)=w" p  "&#x1f6e;"

% Rough breathing and perispomeni
"a(=" p   "&#x1f07;"
"h(=" p   "&#x1f27;"
"i(=" p   "&#x1f37;"
"u(=" p   "&#x1f57;"
"w(=" p   "&#x1f67;"
"*(=a" p  "&#x1f0f;"
"*(=h" p  "&#x1f2f;"
"*(=i" p  "&#x1f3f;"
"*(=u" p  "&#x1f5f;"
"*(=w" p  "&#x1f6f;"

% Perispomeni and ypogegrammeni
"a=|" p   "&#x1fb7;"
"h=|" p   "&#x1fc7;"
"w=|" p   "&#x1ff7;"

% Ypogegrammeni
"a|" p    "&#x1fb3;"
"h|" p    "&#x1fc3;"
"w|" p    "&#x1ff3;"
"*a|" p   "&#x1fbc;"
"*h|" p   "&#x1fcc;"
"*w|" p   "&#x1ffc;"

% Acute accent and ypogegrammeni
"a/|" p   "&#x1fb4;"
"h/|" p   "&#x1fc4;"
"w/|" p   "&#x1ff4;"

% Smooth breathing and ypogegrammeni
"a)|" p   "&#x1f80;"
"h)|" p   "&#x1f90;"
"w)|" p   "&#x1fa0;"
"*)a|" p  "&#x1f88;"
"*)h|" p  "&#x1f98;"
"*)w|" p  "&#x1fa8;"

% Rough breathing and ypogegrammeni
"a(|" p   "&#x1f81;"
"h(|" p   "&#x1f91;"
"w(|" p   "&#x1fa1;"
"*(a|" p  "&#x1f89;"
"*(h|" p  "&#x1f99;"
"*(w|" p  "&#x1fa9;"

% Smooth breathing, acute accent, and ypogegrammeni
"a)\\|" p  "&#x1f82;"
"h)\\|" p  "&#x1f92;"
"w)\\|" p  "&#x1fa2;"
"*)\\a|" p  "&#x1f8a;"
"*)\\h|" p   "&#x1f9a;"
"*)\\w|" p   "&#x1faa;"

% Rough breathing, grave accent, and ypogegrammeni
"a(\\|" 	p  	"&#x1f83;"
"h)\\|" 	p  	"&#x1f93;"
"w)\\|" 	p  	"&#x1fa3;"
"*(\\a|" 	p  	"&#x1f8b;"
"*)\\h|" 	p   "&#x1f9b;"
"*)\\w|" 	p   "&#x1fab;"

% Smooth breathing, accute accent, and ypogegrammeni
"a)/|" p  "&#x1f84;"
"h)/|" p  "&#x1f94;"
"w)/|" p  "&#x1fa4;"
"*)/a|" p   "&#x1f8c;"
"*)/h|" p   "&#x1f9c;"
"*)/w|" p   "&#x1fac;"

% Rough breating, acute accent, and ypogegrammeni
"a(/|" p  "&#x1f85;"
"h(/|" p  "&#x1f95;"
"w(/|" p  "&#x1fa5;"
"*(/a|" p   "&#x1f8d;"
"*(/h|" p   "&#x1f9d;"
"*(/w|" p   "&#x1fad;"

% Smooth breathing, ypogegrammeni, and perispomeni
"a)=|" p  "&#x1f86;"
"h)=|" p  "&#x1f96;"
"w)=|" p  "&#x1fa6;"
"*)=a|" p   "&#x1f8e;"
"*)=h|" p   "&#x1f9e;"
"*)=w|" p   "&#x1fae;"

% Rough breathing, ypogegrammeni, and perispomeni
"a(=|" p  "&#x1f87;"
"h(=|" p  "&#x1f97;"
"w(=|" p  "&#x1fa7;"
"*(=a|" p   "&#x1f8f;"
"*(=h|" p   "&#x1f9f;"
"*(=w|" p   "&#x1faf;"

% Diaeresis
"i+" p    "&#x03ca;"
"*+i" p   "&#x03aa;"
"i\\+" p  "&#x1fd2;"
"i/+" p   "&#x1fd3;"
"i+/" p   "&#x1fd3;"
"i=+" p   "&#x1fd7;"
"u+" p    "&#x03cb;"
"*+u" p   "&#x03ab;"
"u\\+" p  "&#x1fe2;"
"u/+" p   "&#x1fe3;"
"u=+" p   "&#x1fe7;"

% Macron
"a&" p    "&#x1fb0;"
"i&" p    "&#x1fd0;"
"u&" p    "&#x1fe0;"

% Breve
"a'"    p       "&#x1fb1;"
"i'"    p       "&#x1fd1;"
"u'"    p       "&#x1fe1;"

% Basic punctuation
":"     p       "&#x00b7;"
"'"     p       "&#x2019;"
"-"     p       "&#x2010;"
"_"     p       "&#x2014;"

@end

