% classical Greek in my notation to Beta code
% My notation is identical to Yannis Haralambous' notation.

@patterns 0

"<GR>"      1 "<foreign lang=el>"

@patterns 1

"</GR>"     0 "</foreign>"

"a"         p "A"
"A"         p "*A"
"a|"        p "A|"
"A|"        p "*A|"
"<a|"       p "A(|"
"<A|"       p "*(A|"
">a|"       p "A)|"
">A|"       p "*)A|"
"'a|"       p "A/|"
"'A|"       p "*/A|"
"`a|"       p "A\\|"
"`A|"       p "*\\A|"
"=a|"       p "A=|"
"=A|"       p "*=A|"
"<'a|"      p "A(/|"
"<'A|"      p "*(/A|"
">'a|"      p "A)/|"
">'A|"      p "*)/A|"
"<`a|"      p "A(\\|"
"<`A|"      p "*(\\A|"
">`a|"      p "A)\\|"
">`A|"      p "*)\\A|"
"<=a|"      p "A(=|"
"<=A|"      p "*(=A|"
">=a|"      p "A)=|"
">=A|"      p "*)=A|"
"<a"        p "A("
"<A"        p "*(A"
">a"        p "A)"
">A"        p "*)A"
"`a"        p "A\\"
"`A"        p "*\\A"
"'a"        p "A/"
"'A"        p "*/A"
"=a"        p "A="
"=A"        p "*=A"
"<'a"       p "A(/"
"<'A"       p "*(/A"
">'a"       p "A)/"
">'A"       p "*)/A"
"<`a"       p "A(\\"
"<`A"       p "*(\\A"
">`a"       p "A)\\"
">`A"       p "*)\\A"
"<=a"       p "A(="
"<=A"       p "*(=A"
">=a"       p "A)="
">=A"       p "*)=A"

"b"         p "B"
"B"         p "*B"

"g"         p "G"
"G"         p "*G"

"d"         p "D"
"D"         p "*D"

"e"         p "E"
"E"         p "*E"
"<e"        p "&erougr;"
"<E"        p "&Erougr;"
">e"        p "&esmogr;"
">E"        p "&Esmogr;"
"`e"        p "&egragr;"
"`E"        p "&Egragr;"
"'e"        p "&eacugr;"
"'E"        p "&Eacugr;"
"=e"        p "&ecirgr;"
"=E"        p "&Ecirgr;"
"<'e"       p "&eragr;"
"<'E"       p "&Eragr;"
">'e"       p "&esagr;"
">'E"       p "&Esagr;"
"<`e"       p "&erggr;"
"<`E"       p "&Erggr;"
">`e"       p "&esggr;"
">`E"       p "&Esggr;"
"<=e"       p "&ercgr;"
"<=E"       p "&Ercgr;"
">=e"       p "&escgr;"
">=E"       p "&Escgr;"

"z"         p "Z"
"Z"         p "*Z"

"h"         p "H"
"H"         p "*H"
"h|"        p "&eeiotgr;"
"H|"        p "&EEiotgr;"
"<h|"       p "&eerigr;"
"<H|"       p "&EErigr;"
">h|"       p "&eesigr;"
">H|"       p "&EEsigr;"
"'h|"       p "&eeaigr;"
"'H|"       p "&EEaigr;"
"`h|"       p "&eegigr;"
"`H|"       p "&EEgigr;"
"=h|"       p "&eecigr;"
"=H|"       p "&EEcigr;"
"<'h|"      p "&eeraigr;"
"<'H|"      p "&EEraigr;"
">'h|"      p "&eesaigr;"
">'H|"      p "&EEsaigr;"
"<`h|"      p "&eergigr;"
"<`H|"      p "&EErgigr;"
">`h|"      p "&eesgigr;"
">`H|"      p "&EEsgigr;"
"<=h|"      p "&eercigr;"
"<=H|"      p "&EErcigr;"
">=h|"      p "&eescigr;"
">=H|"      p "&EEscigr;"
"<h"        p "&eerougr;"
"<H"        p "&EErougr;"
">h"        p "&eesmogr;"
">H"        p "&EEsmogr;"
"`h"        p "&eegragr;"
"`H"        p "&EEgragr;"
"'h"        p "&eeacugr;"
"'H"        p "&EEacugr;"
"=h"        p "&eecirgr;"
"=H"        p "&EEcirgr;"
"<'h"       p "&eeragr;"
"<'H"       p "&EEragr;"
">'h"       p "&eesagr;"
">'H"       p "&EEsagr;"
"<`h"       p "&eerggr;"
"<`H"       p "&EErggr;"
">`h"       p "&eesggr;"
">`H"       p "&EEsggr;"
"<=h"       p "&eercgr;"
"<=H"       p "&EErcgr;"
">=h"       p "&eescgr;"
">=H"       p "&EEscgr;"

"j"         p "Q"
"J"         p "*Q"

"i"         p "I"
"I"         p "*I"
"<i"        p "&irougr;"
"<I"        p "&Irougr;"
">i"        p "&ismogr;"
">I"        p "&Ismogr;"
"`i"        p "&igragr;"
"`I"        p "&Igragr;"
"'i"        p "&iacugr;"
"'I"        p "&Iacugr;"
"=i"        p "&icirgr;"
"=I"        p "&Icirgr;"
"<'i"       p "&iragr;"
"<'I"       p "&Iragr;"
">'i"       p "&isagr;"
">'I"       p "&Isagr;"
"<`i"       p "&irggr;"
"<`I"       p "&Irggr;"
">`i"       p "&isggr;"
">`I"       p "&Isggr;"
"<=i"       p "&ircgr;"
"<=I"       p "&Ircgr;"
">=i"       p "&iscgr;"
">=I"       p "&Iscgr;"

"k"         p "K"
"K"         p "*K"

"l"         p "L"
"L"         p "*L"

"m"         p "M"
"M"         p "*M"

"n"         p "N"
"N"         p "*N"

"x"         p "C"
"X"         p "*C"

"o"         p "O"
"O"         p "*O"
"<o"        p "&orougr;"
"<O"        p "&Orougr;"
">o"        p "&osmogr;"
">O"        p "&Osmogr;"
"`o"        p "&ogragr;"
"`O"        p "&Ogragr;"
"'o"        p "&oacugr;"
"'O"        p "&Oacugr;"
"=o"        p "&ocirgr;"
"=O"        p "&Ocirgr;"
"<'o"       p "&oragr;"
"<'O"       p "&Oragr;"
">'o"       p "&osagr;"
">'O"       p "&Osagr;"
"<`o"       p "&orggr;"
"<`O"       p "&Orggr;"
">`o"       p "&osggr;"
">`O"       p "&Osggr;"
"<=o"       p "&orcgr;"
"<=O"       p "&Orcgr;"
">=o"       p "&oscgr;"
">=O"       p "&Oscgr;"

"p"         p "P"
"P"         p "*P"

"r"         p "R"
"R"         p "*R"
"<r"        p "R("
"<R"        p "*(R"

"s"         p "S1"
"S"         p "*S"
"c"         p "S2"

"t"         p "T"
"T"         p "*T"

"u"         p "U"
"U"         p "*U"
"<u"        p "&urougr;"
"<U"        p "&Urougr;"
">u"        p "&usmogr;"
">U"        p "&Usmogr;"
"`u"        p "&ugragr;"
"`U"        p "&Ugragr;"
"'u"        p "&uacugr;"
"'U"        p "&Uacugr;"
"=u"        p "&ucirgr;"
"=U"        p "&Ucirgr;"
"<'u"       p "&uragr;"
"<'U"       p "&Uragr;"
">'u"       p "&usagr;"
">'U"       p "&Usagr;"
"<`u"       p "&urggr;"
"<`U"       p "&Urggr;"
">`u"       p "&usggr;"
">`U"       p "&Usggr;"
"<=u"       p "&urcgr;"
"<=U"       p "&Urcgr;"
">=u"       p "&uscgr;"
">=U"       p "&Uscgr;"

"f"         p "F"
"F"         p "*F"

"q"         p "X"
"Q"         p "*X"

"y"         p "Y"
"Y"         p "*Y"

"w"         p "W"
"W"         p "*W"
"w|"        p "&ohiotgr;"
"W|"        p "&OHiotgr;"
"<w|"       p "&ohrigr;"
"<W|"       p "&OHrigr;"
">w|"       p "&ohsigr;"
">W|"       p "&OHsigr;"
"'w|"       p "&ohaigr;"
"'W|"       p "&OHaigr;"
"`w|"       p "&ohgigr;"
"`W|"       p "&OHgigr;"
"=w|"       p "&ohcigr;"
"=W|"       p "&OHcigr;"
"<'w|"      p "&ohraigr;"
"<'W|"      p "&OHraigr;"
">'w|"      p "&ohsaigr;"
">'W|"      p "&OHsaigr;"
"<`w|"      p "&ohrgigr;"
"<`W|"      p "&OHrgigr;"
">`w|"      p "&ohsgigr;"
">`W|"      p "&OHsgigr;"
"<=w|"      p "&ohrcigr;"
"<=W|"      p "&OHrcigr;"
">=w|"      p "&ohscigr;"
">=W|"      p "&OHscigr;"
"<w"        p "&ohrougr;"
"<W"        p "&OHrougr;"
">w"        p "&ohsmogr;"
">W"        p "&OHsmogr;"
"`w"        p "&ohgragr;"
"`W"        p "&OHgragr;"
"'w"        p "&ohacugr;"
"'W"        p "&OHacugr;"
"=w"        p "&ohcirgr;"
"=W"        p "&OHcirgr;"
"<'w"       p "&ohragr;"
"<'W"       p "&OHragr;"
">'w"       p "&ohsagr;"
">'W"       p "&OHsagr;"
"<`w"       p "&ohrggr;"
"<`W"       p "&OHrggr;"
">`w"       p "&ohsggr;"
">`W"       p "&OHsggr;"
"<=w"       p "&ohrcgr;"
"<=W"       p "&OHrcgr;"
">=w"       p "&ohscgr;"
">=W"       p "&OHscgr;"

% punctuation marks

"&middot;"  p ":"
";"         p ";"

"&apos;"    p "'"
"&prime;"   p "&prime;"

%% additional entities not in TEI

"\\=a"       p "A%26"
"\\=A"       p "*A%26"
")a"        p "A%27"
")A"        p "*A%27"

%% warn for illegal characters

"v"         e "illegal character v"
"V"         e "illegal character V"
"C"         e "illegal character C"
"<"         e "stand alone <"
"'"         e "stand alone '"
">"         e "stand alone >"
"\""        e "stand alone \""
"`"         e "stand alone `"
"["         e "illegal character ["
"]"         e "illegal character ]"

@end
