% Classical Greek in TEI entities to Unicode UTF8

"&agr;"     p "α"     % "a"
"&Agr;"     p "Α"     % "A"
"&aiotgr;"  p "ᾳ"    % "a|"
"&Aiotgr;"  p "ᾼ"    % "A|"
"&arigr;"   p "ᾁ"    % "<a|"
"&Arigr;"   p "ᾉ"    % "<A|"
"&asigr;"   p "ᾀ"    % ">a|"
"&Asigr;"   p "ᾈ"    % ">A|"
"&aaigr;"   p "ᾴ"    % "'a|"
"&Aaigr;"   p "Άͅ"   % "'A|"
"&agigr;"   p "ᾲ"    % "`a|"
"&Agigr;"   p "Ὰͅ"   % "`A|"
"&acigr;"   p "ᾷ"    % "=a|"
"&Acigr;"   p "ᾼ͂"   % "=A|"
"&araigr;"  p "ᾅ"    % "<'a|"
"&Araigr;"  p "ᾍ"    % "<'A|"
"&asaigr;"  p "ᾄ"    % ">'a|"
"&Asaigr;"  p "ᾌ"    % ">'A|"
"&argigr;"  p "ᾃ"    % "<`a|"
"&Argigr;"  p "ᾋ"    % "<`A|"
"&asgigr;"  p "ᾂ"    % ">`a|"
"&Asgigr;"  p "ᾊ"    % ">`A|"
"&arcigr;"  p "ᾇ"    % "<=a|"
"&Arcigr;"  p "ᾏ"    % "<=A|"
"&ascigr;"  p "ᾇ"    % ">=a|"
"&Ascigr;"  p "ᾎ"    % ">=A|"
"&arougr;"  p "ἁ"    % "<a"
"&Arougr;"  p "Ἁ"    % "<A"
"&asmogr;"  p "ἀ"    % ">a"
"&Asmogr;"  p "Ἀ"    % ">A"
"&agragr;"  p "ὰ"    % "`a"
"&Agragr;"  p "Ὰ"    % "`A"
"&aacugr;"  p "ά"    % "'a"
"&Aacugr;"  p "Ά"    % "'A"
"&acirgr;"  p "ᾶ"    % "=a"
"&Acirgr;"  p "Α͂"  % "=A"
"&aragr;"   p "ἅ"    % "<'a"
"&Aragr;"   p "Ἅ"    % "<'A"
"&asagr;"   p "ἄ"    % ">'a"
"&Asagr;"   p "Ἄ"    % ">'A"
"&arggr;"   p "ἃ"    % "<`a"
"&Arggr;"   p "Ἃ"    % "<`A"
"&asggr;"   p "ἂ"    % ">`a"
"&Asggr;"   p "Ἂ"    % ">`A"
"&arcgr;"   p "ἇ"    % "<=a"
"&Arcgr;"   p "Ἇ"    % "<=A"
"&ascgr;"   p "ἆ"    % ">=a"
"&Ascgr;"   p "Ἆ"    % ">=A"

"&bgr;"     p "β"     % "b"
"&Bgr;"     p "Β"     % "B"

"&ggr;"     p "γ"     % "g"
"&Ggr;"     p "Γ"     % "G"

"&dgr;"     p "δ"     % "d"
"&Dgr;"     p "Δ"     % "D"

"&egr;"     p "ε"     % "e"
"&Egr;"     p "Ε"     % "E"
"&erougr;"  p "ἑ"    % "<e"
"&Erougr;"  p "Ἑ"    % "<E"
"&esmogr;"  p "ἐ"    % ">e"
"&Esmogr;"  p "Ἐ"    % ">E"
"&egragr;"  p "ὲ"    % "`e"
"&Egragr;"  p "Ὲ"    % "`E"
"&eacugr;"  p "έ"    % "'e"
"&Eacugr;"  p "Έ"    % "'E"
"&ecirgr;"  p "ε͂"  % "=e"
"&Ecirgr;"  p "Ε͂"  % "=E"
"&eragr;"   p "ἕ"    % "<'e"
"&Eragr;"   p "Ἕ"    % "<'E"
"&esagr;"   p "ἔ"    % ">'e"
"&Esagr;"   p "Ἔ"    % ">'E"
"&erggr;"   p "ἓ"    % "<`e"
"&Erggr;"   p "Ἓ"    % "<`E"
"&esggr;"   p "ἒ"    % ">`e"
"&Esggr;"   p "Ἒ"    % ">`E"
"&ercgr;"   p "ἑ͂"   % "<=e"
"&Ercgr;"   p "Ἑ͂"   % "<=E"
"&escgr;"   p "ἐ͂"   % ">=e"
"&Escgr;"   p "Ἐ͂"   % ">=E"

"&zgr;"     p "ζ"     % "z"
"&Zgr;"     p "Ζ"     % "Z"

"&eegr;"    p "η"     % "h"
"&EEgr;"    p "Η"     % "H"
"&eeiotgr;" p "ῃ"    % "h|"
"&EEiotgr;" p "ῌ"    % "H|"
"&eerigr;"  p "ᾑ"    % "<h|"
"&EErigr;"  p "ᾙ"    % "<H|"
"&eesigr;"  p "ᾐ"    % ">h|"
"&EEsigr;"  p "ᾘ"    % ">H|"
"&eeaigr;"  p "ῄ"    % "'h|"
"&EEaigr;"  p "Ήͅ"   % "'H|"
"&eegigr;"  p "ῂ"    % "`h|"
"&EEgigr;"  p "Ὴͅ"   % "`H|"
"&eecigr;"  p "ῇ"    % "=h|"
"&EEcigr;"  p "ῌ͂"   % "=H|"
"&eeraigr;" p "ᾕ"    % "<'h|"
"&EEraigr;" p "ᾝ"    % "<'H|"
"&eesaigr;" p "ᾔ"    % ">'h|"
"&EEsaigr;" p "ᾜ"    % ">'H|"
"&eergigr;" p "ᾓ"    % "<`h|"
"&EErgigr;" p "ᾛ"    % "<`H|"
"&eesgigr;" p "ᾒ"    % ">`h|"
"&EEsgigr;" p "ᾚ"    % ">`H|"
"&eercigr;" p "ᾗ"    % "<=h|"
"&EErcigr;" p "ᾟ"    % "<=H|"
"&eescigr;" p "ᾖ"    % ">=h|"
"&EEscigr;" p "ᾞ"    % ">=H|"
"&eerougr;" p "ἡ"    % "<h"
"&EErougr;" p "Ἡ"    % "<H"
"&eesmogr;" p "ἠ"    % ">h"
"&EEsmogr;" p "Ἠ"    % ">H"
"&eegragr;" p "ὴ"    % "`h"
"&EEgragr;" p "Ὴ"    % "`H"
"&eeacugr;" p "ή"    % "'h"
"&EEacugr;" p "Ή"    % "'H"
"&eecirgr;" p "ῆ"    % "=h"
"&EEcirgr;" p "Η͂"  % "=H"
"&eeragr;"  p "ἥ"    % "<'h"
"&EEragr;"  p "Ἥ"    % "<'H"
"&eesagr;"  p "ἤ"    % ">'h"
"&EEsagr;"  p "Ἤ"    % ">'H"
"&eerggr;"  p "ἣ"    % "<`h"
"&EErggr;"  p "Ἣ"    % "<`H"
"&eesggr;"  p "ἢ"    % ">`h"
"&EEsggr;"  p "Ἢ"    % ">`H"
"&eercgr;"  p "ἧ"    % "<=h"
"&EErcgr;"  p "Ἧ"    % "<=H"
"&eescgr;"  p "ἦ"    % ">=h"
"&EEscgr;"  p "Ἦ"    % ">=H"

"&thgr;"    p "θ"     % "j"
"&THgr;"    p "Θ"     % "J"

"&igr;"     p "ι"     % "i"
"&Igr;"     p "Ι"     % "I"
"&irougr;"  p "ἱ"    % "<i"
"&Irougr;"  p "Ἱ"    % "<I"
"&ismogr;"  p "ἰ"    % ">i"
"&Ismogr;"  p "Ἰ"    % ">I"
"&igragr;"  p "ὶ"    % "`i"
"&Igragr;"  p "Ὶ"    % "`I"
"&iacugr;"  p "ί"    % "'i"
"&Iacugr;"  p "Ί"    % "'I"
"&icirgr;"  p "ῖ"    % "=i"
"&Icirgr;"  p "Ι͂"  % "=I"
"&iragr;"   p "ἵ"    % "<'i"
"&Iragr;"   p "Ἵ"    % "<'I"
"&isagr;"   p "ἴ"    % ">'i"
"&Isagr;"   p "Ἴ"    % ">'I"
"&irggr;"   p "ἳ"    % "<`i"
"&Irggr;"   p "Ἳ"    % "<`I"
"&isggr;"   p "ἲ"    % ">`i"
"&Isggr;"   p "Ἲ"    % ">`I"
"&ircgr;"   p "ἷ"    % "<=i"
"&Ircgr;"   p "Ἷ"    % "<=I"
"&iscgr;"   p "ἶ"    % ">=i"
"&Iscgr;"   p "Ἶ"    % ">=I"

"&kgr;"     p "κ"     % "k"
"&Kgr;"     p "Κ"     % "K"

"&lgr;"     p "λ"     % "l"
"&Lgr;"     p "Λ"     % "L"

"&mgr;"     p "μ"     % "m"
"&Mgr;"     p "Μ"     % "M"

"&ngr;"     p "ν"     % "n"
"&Ngr;"     p "Ν"     % "N"

"&xgr;"     p "ξ"     % "x"
"&Xgr;"     p "Ξ"     % "X"

"&ogr;"     p "ο"     % "o"
"&Ogr;"     p "Ο"     % "O"
"&orougr;"  p "ὁ"    % "<o"
"&Orougr;"  p "Ὁ"    % "<O"
"&osmogr;"  p "ὀ"    % ">o"
"&Osmogr;"  p "Ὀ"    % ">O"
"&ogragr;"  p "ὸ"    % "`o"
"&Ogragr;"  p "Ὸ"    % "`O"
"&oacugr;"  p "ό"    % "'o"
"&Oacugr;"  p "Ό"    % "'O"
"&ocirgr;"  p "ο͂"  % "=o"
"&Ocirgr;"  p "Ο͂"  % "=O"
"&oragr;"   p "ὅ"    % "<'o"
"&Oragr;"   p "Ὅ"    % "<'O"
"&osagr;"   p "ὄ"    % ">'o"
"&Osagr;"   p "Ὄ"    % ">'O"
"&orggr;"   p "ὃ"    % "<`o"
"&Orggr;"   p "Ὃ"    % "<`O"
"&osggr;"   p "ὂ"    % ">`o"
"&Osggr;"   p "Ὂ"    % ">`O"
"&orcgr;"   p "ὁ͂"   % "<=o"
"&Orcgr;"   p "Ὁ͂"   % "<=O"
"&oscgr;"   p "ὀ͂"   % ">=o"
"&Oscgr;"   p "Ὀ͂"   % ">=O"

"&pgr;"     p "π"     % "p"
"&Pgr;"     p "Π"     % "P"

"&rgr;"     p "ρ"     % "r"
"&Rgr;"     p "Ρ"     % "R"
"&rrougr;"  p "ῥ"    % "<r"
"&Rrougr;"  p "Ῥ"    % "<R"

"&sgr;"     p "σ"     % "s"
"&Sgr;"     p "Σ"     % "S"
"&sfgr;"    p "ς"     % "c"

"&tgr;"     p "τ"     % "t"
"&Tgr;"     p "Τ"     % "T"

"&ugr;"     p "υ"     % "u"
"&Ugr;"     p "Υ"     % "U"
"&urougr;"  p "ὑ"    % "<u"
"&Urougr;"  p "Ὑ"    % "<U"
"&usmogr;"  p "ὐ"    % ">u"
"&Usmogr;"  p "Υ̓"  % ">U"
"&ugragr;"  p "ὺ"    % "`u"
"&Ugragr;"  p "Ὺ"    % "`U"
"&uacugr;"  p "ύ"    % "'u"
"&Uacugr;"  p "Ύ"    % "'U"
"&ucirgr;"  p "ῡ"    % "=u"
"&Ucirgr;"  p "Ῡ"    % "=U"
"&uragr;"   p "ὕ"    % "<'u"
"&Uragr;"   p "Ὕ"    % "<'U"
"&usagr;"   p "ὔ"    % ">'u"
"&Usagr;"   p "Υ̓́"   % ">'U"
"&urggr;"   p "ὓ"    % "<`u"
"&Urggr;"   p "Ὓ"    % "<`U"
"&usggr;"   p "ὒ"    % ">`u"
"&Usggr;"   p "Υ̓̀"   % ">`U"
"&urcgr;"   p "ὗ"    % "<=u"
"&Urcgr;"   p "Ὗ"    % "<=U"
"&uscgr;"   p "ὖ"    % ">=u"
"&Uscgr;"   p "Υ̓͂"   % ">=U"

"&phgr;"    p "φ"     % "f"
"&PHgr;"    p "Φ"     % "F"

"&khgr;"    p "χ"     % "q"
"&KHgr;"    p "Χ"     % "Q"

"&psgr;"    p "ψ"     % "y"
"&PSgr;"    p "Ψ"     % "Y"

"&ohgr;"    p "ω"     % "w"
"&OHgr;"    p "Ω"     % "W"
"&ohiotgr;" p "ῳ"    % "w|"
"&OHiotgr;" p "ῼ"    % "W|"
"&ohrigr;"  p "ᾡ"    % "<w|"
"&OHrigr;"  p "ᾩ"    % "<W|"
"&ohsigr;"  p "ᾠ"    % ">w|"
"&OHsigr;"  p "ᾨ"    % ">W|"
"&ohaigr;"  p "ῴ"    % "'w|"
"&OHaigr;"  p "Ώͅ" % "'W|"
"&ohgigr;"  p "ῲ"    % "`w|"
"&OHgigr;"  p "Ὼͅ" % "`W|"
"&ohcigr;"  p "ῷ"    % "=w|"
"&OHcigr;"  p "ῼ͂"   % "=W|"
"&ohraigr;" p "ᾥ"    % "<'w|"
"&OHraigr;" p "ᾭ"    % "<'W|"
"&ohsaigr;" p "ᾤ"    % ">'w|"
"&OHsaigr;" p "ᾬ"    % ">'W|"
"&ohrgigr;" p "ᾣ"    % "<`w|"
"&OHrgigr;" p "ᾫ"    % "<`W|"
"&ohsgigr;" p "ᾢ"    % ">`w|"
"&OHsgigr;" p "ᾪ"    % ">`W|"
"&ohrcigr;" p "ᾧ"    % "<=w|"
"&OHrcigr;" p "ᾯ"    % "<=W|"
"&ohscigr;" p "ᾦ"    % ">=w|"
"&OHscigr;" p "ᾮ"    % ">=W|"
"&ohrougr;" p "ὡ"    % "<w"
"&OHrougr;" p "Ὡ"    % "<W"
"&ohsmogr;" p "ὠ"    % ">w"
"&OHsmogr;" p "Ὠ"    % ">W"
"&ohgragr;" p "ὼ"    % "`w"
"&OHgragr;" p "Ὼ"    % "`W"
"&ohacugr;" p "ώ"    % "'w"
"&OHacugr;" p "Ώ"    % "'W"
"&ohcirgr;" p "ῶ"    % "=w"
"&OHcirgr;" p "Ω͂"  % "=W"
"&ohragr;"  p "ὥ"    % "<'w"
"&OHragr;"  p "Ὥ"    % "<'W"
"&ohsagr;"  p "ὤ"    % ">'w"
"&OHsagr;"  p "Ὤ"    % ">'W"
"&ohrggr;"  p "ὣ"    % "<`w"
"&OHrggr;"  p "Ὣ"    % "<`W"
"&ohsggr;"  p "ὢ"    % ">`w"
"&OHsggr;"  p "Ὢ"    % ">`W"
"&ohrcgr;"  p "ὧ"    % "<=w"
"&OHrcgr;"  p "Ὧ"    % "<=W"
"&ohscgr;"  p "ὦ"    % ">=w"
"&OHscgr;"  p "Ὦ"    % ">=W"

% punctuation marks

"&ckgr;"    p "·"     % "·"
"&qmgr;"    p ";"     % ";"

"&apos;"    p "ʼ"     % "&apos;"
"′"   p "′"    % "′"

%% additional entities not in TEI

"&amacgr;"  p "ᾱ"  % "\=a"
"&Amacgr;"  p "Ᾱ"  % "\=A"
"&abregr;"  p "ᾰ"  % ")a"
"&Abregr;"  p "Ᾰ"  % ")A"

