% Classical Greek in TEI entities to XML numeric entities

"&agr;"     p "&#x3b1;"     % "a"
"&Agr;"     p "&#x391;"     % "A"
"&aiotgr;"  p "&#x1fb3;"    % "a|"
"&Aiotgr;"  p "&#x1fbc;"    % "A|"
"&arigr;"   p "&#x1f81;"    % "<a|"
"&Arigr;"   p "&#x1f89;"    % "<A|"
"&asigr;"   p "&#x1f80;"    % ">a|"
"&Asigr;"   p "&#x1f88;"    % ">A|"
"&aaigr;"   p "&#x1fb4;"    % "'a|"
"&Aaigr;"   p "&#x391;&#x301;&#x345;"   % "'A|"
"&agigr;"   p "&#x1fb2;"    % "`a|"
"&Agigr;"   p "&#x391;&#x300;&#x345;"   % "`A|"
"&acigr;"   p "&#x1fb7;"    % "=a|"
"&Acigr;"   p "&#x391;&#x342;&#x345;"   % "=A|"
"&araigr;"  p "&#x1f85;"    % "<'a|"
"&Araigr;"  p "&#x1f8d;"    % "<'A|"
"&asaigr;"  p "&#x1f84;"    % ">'a|"
"&Asaigr;"  p "&#x1f8c;"    % ">'A|"
"&argigr;"  p "&#x1f83;"    % "<`a|"
"&Argigr;"  p "&#x1f8b;"    % "<`A|"
"&asgigr;"  p "&#x1f82;"    % ">`a|"
"&Asgigr;"  p "&#x1f8a;"    % ">`A|"
"&arcigr;"  p "&#x1f87;"    % "<=a|"
"&Arcigr;"  p "&#x1f8f;"    % "<=A|"
"&ascigr;"  p "&#x1f87;"    % ">=a|"
"&Ascigr;"  p "&#x1f8e;"    % ">=A|"
"&arougr;"  p "&#x1f01;"    % "<a"
"&Arougr;"  p "&#x1f09;"    % "<A"
"&asmogr;"  p "&#x1f00;"    % ">a"
"&Asmogr;"  p "&#x1f08;"    % ">A"
"&agragr;"  p "&#x1f70;"    % "`a"
"&Agragr;"  p "&#x1fba;"    % "`A"
"&aacugr;"  p "&#x1f71;"    % "'a"
"&Aacugr;"  p "&#x1fbb;"    % "'A"
"&acirgr;"  p "&#x1fb6;"    % "=a"
"&Acirgr;"  p "&#x391;&#x342;"  % "=A"
"&aragr;"   p "&#x1f05;"    % "<'a"
"&Aragr;"   p "&#x1f0d;"    % "<'A"
"&asagr;"   p "&#x1f04;"    % ">'a"
"&Asagr;"   p "&#x1f0c;"    % ">'A"
"&arggr;"   p "&#x1f03;"    % "<`a"
"&Arggr;"   p "&#x1f0b;"    % "<`A"
"&asggr;"   p "&#x1f02;"    % ">`a"
"&Asggr;"   p "&#x1f0a;"    % ">`A"
"&arcgr;"   p "&#x1f07;"    % "<=a"
"&Arcgr;"   p "&#x1f0f;"    % "<=A"
"&ascgr;"   p "&#x1f06;"    % ">=a"
"&Ascgr;"   p "&#x1f0e;"    % ">=A"

"&bgr;"     p "&#x3b2;"     % "b"
"&Bgr;"     p "&#x392;"     % "B"

"&ggr;"     p "&#x3b3;"     % "g"
"&Ggr;"     p "&#x393;"     % "G"

"&dgr;"     p "&#x3b4;"     % "d"
"&Dgr;"     p "&#x394;"     % "D"

"&egr;"     p "&#x3b5;"     % "e"
"&Egr;"     p "&#x395;"     % "E"
"&erougr;"  p "&#x1f11;"    % "<e"
"&Erougr;"  p "&#x1f19;"    % "<E"
"&esmogr;"  p "&#x1f10;"    % ">e"
"&Esmogr;"  p "&#x1f18;"    % ">E"
"&egragr;"  p "&#x1f72;"    % "`e"
"&Egragr;"  p "&#x1fc8;"    % "`E"
"&eacugr;"  p "&#x1f73;"    % "'e"
"&Eacugr;"  p "&#x1fc9;"    % "'E"
"&ecirgr;"  p "&#x3b5;&#x342;"  % "=e"
"&Ecirgr;"  p "&#x395;&#x342;"  % "=E"
"&eragr;"   p "&#x1f15;"    % "<'e"
"&Eragr;"   p "&#x1f1d;"    % "<'E"
"&esagr;"   p "&#x1f14;"    % ">'e"
"&Esagr;"   p "&#x1f1c;"    % ">'E"
"&erggr;"   p "&#x1f13;"    % "<`e"
"&Erggr;"   p "&#x1f1b;"    % "<`E"
"&esggr;"   p "&#x1f12;"    % ">`e"
"&Esggr;"   p "&#x1f1a;"    % ">`E"
"&ercgr;"   p "&#x3b5;&#x314;&#x342;"   % "<=e"
"&Ercgr;"   p "&#x395;&#x314;&#x342;"   % "<=E"
"&escgr;"   p "&#x3b5;&#x313;&#x342;"   % ">=e"
"&Escgr;"   p "&#x395;&#x313;&#x342;"   % ">=E"

"&zgr;"     p "&#x3b6;"     % "z"
"&Zgr;"     p "&#x396;"     % "Z"

"&eegr;"    p "&#x3b7;"     % "h"
"&EEgr;"    p "&#x397;"     % "H"
"&eeiotgr;" p "&#x1fc3;"    % "h|"
"&EEiotgr;" p "&#x1fcc;"    % "H|"
"&eerigr;"  p "&#x1f91;"    % "<h|"
"&EErigr;"  p "&#x1f99;"    % "<H|"
"&eesigr;"  p "&#x1f90;"    % ">h|"
"&EEsigr;"  p "&#x1f98;"    % ">H|"
"&eeaigr;"  p "&#x1fc4;"    % "'h|"
"&EEaigr;"  p "&#x397;&#x301;&#x345;"   % "'H|"
"&eegigr;"  p "&#x1fc2;"    % "`h|"
"&EEgigr;"  p "&#x397;&#x300;&#x345;"   % "`H|"
"&eecigr;"  p "&#x1fc7;"    % "=h|"
"&EEcigr;"  p "&#x397;&#x342;&#x345;"   % "=H|"
"&eeraigr;" p "&#x1f95;"    % "<'h|"
"&EEraigr;" p "&#x1f9d;"    % "<'H|"
"&eesaigr;" p "&#x1f94;"    % ">'h|"
"&EEsaigr;" p "&#x1f9c;"    % ">'H|"
"&eergigr;" p "&#x1f93;"    % "<`h|"
"&EErgigr;" p "&#x1f9b;"    % "<`H|"
"&eesgigr;" p "&#x1f92;"    % ">`h|"
"&EEsgigr;" p "&#x1f9a;"    % ">`H|"
"&eercigr;" p "&#x1f97;"    % "<=h|"
"&EErcigr;" p "&#x1f9f;"    % "<=H|"
"&eescigr;" p "&#x1f96;"    % ">=h|"
"&EEscigr;" p "&#x1f9e;"    % ">=H|"
"&eerougr;" p "&#x1f21;"    % "<h"
"&EErougr;" p "&#x1f29;"    % "<H"
"&eesmogr;" p "&#x1f20;"    % ">h"
"&EEsmogr;" p "&#x1f28;"    % ">H"
"&eegragr;" p "&#x1f74;"    % "`h"
"&EEgragr;" p "&#x1fca;"    % "`H"
"&eeacugr;" p "&#x1f75;"    % "'h"
"&EEacugr;" p "&#x1fcb;"    % "'H"
"&eecirgr;" p "&#x1fc6;"    % "=h"
"&EEcirgr;" p "&#x397;&#x342;"  % "=H"
"&eeragr;"  p "&#x1f25;"    % "<'h"
"&EEragr;"  p "&#x1f2d;"    % "<'H"
"&eesagr;"  p "&#x1f24;"    % ">'h"
"&EEsagr;"  p "&#x1f2c;"    % ">'H"
"&eerggr;"  p "&#x1f23;"    % "<`h"
"&EErggr;"  p "&#x1f2b;"    % "<`H"
"&eesggr;"  p "&#x1f22;"    % ">`h"
"&EEsggr;"  p "&#x1f2a;"    % ">`H"
"&eercgr;"  p "&#x1f27;"    % "<=h"
"&EErcgr;"  p "&#x1f2f;"    % "<=H"
"&eescgr;"  p "&#x1f26;"    % ">=h"
"&EEscgr;"  p "&#x1f2e;"    % ">=H"

"&thgr;"    p "&#x3b8;"     % "j"
"&THgr;"    p "&#x398;"     % "J"

"&igr;"     p "&#x3b9;"     % "i"
"&Igr;"     p "&#x399;"     % "I"
"&irougr;"  p "&#x1f31;"    % "<i"
"&Irougr;"  p "&#x1f39;"    % "<I"
"&ismogr;"  p "&#x1f30;"    % ">i"
"&Ismogr;"  p "&#x1f38;"    % ">I"
"&igragr;"  p "&#x1f76;"    % "`i"
"&Igragr;"  p "&#x1fda;"    % "`I"
"&iacugr;"  p "&#x1f77;"    % "'i"
"&Iacugr;"  p "&#x1fdb;"    % "'I"
"&icirgr;"  p "&#x1fd6;"    % "=i"
"&Icirgr;"  p "&#x399;&#x342;"  % "=I"
"&iragr;"   p "&#x1f35;"    % "<'i"
"&Iragr;"   p "&#x1f3d;"    % "<'I"
"&isagr;"   p "&#x1f34;"    % ">'i"
"&Isagr;"   p "&#x1f3c;"    % ">'I"
"&irggr;"   p "&#x1f33;"    % "<`i"
"&Irggr;"   p "&#x1f3b;"    % "<`I"
"&isggr;"   p "&#x1f32;"    % ">`i"
"&Isggr;"   p "&#x1f3a;"    % ">`I"
"&ircgr;"   p "&#x1f37;"    % "<=i"
"&Ircgr;"   p "&#x1f3f;"    % "<=I"
"&iscgr;"   p "&#x1f36;"    % ">=i"
"&Iscgr;"   p "&#x1f3e;"    % ">=I"

"&kgr;"     p "&#x3ba;"     % "k"
"&Kgr;"     p "&#x39a;"     % "K"

"&lgr;"     p "&#x3bb;"     % "l"
"&Lgr;"     p "&#x39b;"     % "L"

"&mgr;"     p "&#x3bc;"     % "m"
"&Mgr;"     p "&#x39c;"     % "M"

"&ngr;"     p "&#x3bd;"     % "n"
"&Ngr;"     p "&#x39d;"     % "N"

"&xgr;"     p "&#x3be;"     % "x"
"&Xgr;"     p "&#x39e;"     % "X"

"&ogr;"     p "&#x3bf;"     % "o"
"&Ogr;"     p "&#x39f;"     % "O"
"&orougr;"  p "&#x1f41;"    % "<o"
"&Orougr;"  p "&#x1f49;"    % "<O"
"&osmogr;"  p "&#x1f40;"    % ">o"
"&Osmogr;"  p "&#x1f48;"    % ">O"
"&ogragr;"  p "&#x1f78;"    % "`o"
"&Ogragr;"  p "&#x1ff8;"    % "`O"
"&oacugr;"  p "&#x1f79;"    % "'o"
"&Oacugr;"  p "&#x1ff9;"    % "'O"
"&ocirgr;"  p "&#x3bf;&#x342;"  % "=o"
"&Ocirgr;"  p "&#x39f;&#x342;"  % "=O"
"&oragr;"   p "&#x1f45;"    % "<'o"
"&Oragr;"   p "&#x1f4d;"    % "<'O"
"&osagr;"   p "&#x1f44;"    % ">'o"
"&Osagr;"   p "&#x1f4c;"    % ">'O"
"&orggr;"   p "&#x1f43;"    % "<`o"
"&Orggr;"   p "&#x1f4b;"    % "<`O"
"&osggr;"   p "&#x1f42;"    % ">`o"
"&Osggr;"   p "&#x1f4a;"    % ">`O"
"&orcgr;"   p "&#x3bf;&#x314;&#x342;"   % "<=o"
"&Orcgr;"   p "&#x39f;&#x314;&#x342;"   % "<=O"
"&oscgr;"   p "&#x3bf;&#x313;&#x342;"   % ">=o"
"&Oscgr;"   p "&#x39f;&#x313;&#x342;"   % ">=O"

"&pgr;"     p "&#x3c0;"     % "p"
"&Pgr;"     p "&#x3a0;"     % "P"

"&rgr;"     p "&#x3c1;"     % "r"
"&Rgr;"     p "&#x3a1;"     % "R"
"&rrougr;"  p "&#x1fe5;"    % "<r"
"&Rrougr;"  p "&#x1fec;"    % "<R"

"&sgr;"     p "&#x3c3;"     % "s"
"&Sgr;"     p "&#x3a3;"     % "S"
"&sfgr;"    p "&#x3c2;"     % "c"

"&tgr;"     p "&#x3c4;"     % "t"
"&Tgr;"     p "&#x3a4;"     % "T"

"&ugr;"     p "&#x3c5;"     % "u"
"&Ugr;"     p "&#x3a5;"     % "U"
"&urougr;"  p "&#x1f51;"    % "<u"
"&Urougr;"  p "&#x1f59;"    % "<U"
"&usmogr;"  p "&#x1f50;"    % ">u"
"&Usmogr;"  p "&#x3a5;&#x313;"  % ">U"
"&ugragr;"  p "&#x1f7a;"    % "`u"
"&Ugragr;"  p "&#x1fea;"    % "`U"
"&uacugr;"  p "&#x1f7b;"    % "'u"
"&Uacugr;"  p "&#x1feb;"    % "'U"
"&ucirgr;"  p "&#x1fe1;"    % "=u"
"&Ucirgr;"  p "&#x1fe9;"    % "=U"
"&uragr;"   p "&#x1f55;"    % "<'u"
"&Uragr;"   p "&#x1f5d;"    % "<'U"
"&usagr;"   p "&#x1f54;"    % ">'u"
"&Usagr;"   p "&#x3a5;&#x313;&#x301;"   % ">'U"
"&urggr;"   p "&#x1f53;"    % "<`u"
"&Urggr;"   p "&#x1f5b;"    % "<`U"
"&usggr;"   p "&#x1f52;"    % ">`u"
"&Usggr;"   p "&#x3a5;&#x313;&#x300;"   % ">`U"
"&urcgr;"   p "&#x1f57;"    % "<=u"
"&Urcgr;"   p "&#x1f5f;"    % "<=U"
"&uscgr;"   p "&#x1f56;"    % ">=u"
"&Uscgr;"   p "&#x3a5;&#x313;&#x342;"   % ">=U"

"&phgr;"    p "&#x3c6;"     % "f"
"&PHgr;"    p "&#x3a6;"     % "F"

"&khgr;"    p "&#x3c7;"     % "q"
"&KHgr;"    p "&#x3a7;"     % "Q"

"&psgr;"    p "&#x3c8;"     % "y"
"&PSgr;"    p "&#x3a8;"     % "Y"

"&ohgr;"    p "&#x3c9;"     % "w"
"&OHgr;"    p "&#x3a9;"     % "W"
"&ohiotgr;" p "&#x1ff3;"    % "w|"
"&OHiotgr;" p "&#x1ffc;"    % "W|"
"&ohrigr;"  p "&#x1fa1;"    % "<w|"
"&OHrigr;"  p "&#x1fa9;"    % "<W|"
"&ohsigr;"  p "&#x1fa0;"    % ">w|"
"&OHsigr;"  p "&#x1fa8;"    % ">W|"
"&ohaigr;"  p "&#x1ff4;"    % "'w|"
"&OHaigr;"  p "&#x1ffb;&#x345;" % "'W|"
"&ohgigr;"  p "&#x1ff2;"    % "`w|"
"&OHgigr;"  p "&#x1ffa;&#x345;" % "`W|"
"&ohcigr;"  p "&#x1ff7;"    % "=w|"
"&OHcigr;"  p "&#x3a9;&#x342;&#x345;"   % "=W|"
"&ohraigr;" p "&#x1fa5;"    % "<'w|"
"&OHraigr;" p "&#x1fad;"    % "<'W|"
"&ohsaigr;" p "&#x1fa4;"    % ">'w|"
"&OHsaigr;" p "&#x1fac;"    % ">'W|"
"&ohrgigr;" p "&#x1fa3;"    % "<`w|"
"&OHrgigr;" p "&#x1fab;"    % "<`W|"
"&ohsgigr;" p "&#x1fa2;"    % ">`w|"
"&OHsgigr;" p "&#x1faa;"    % ">`W|"
"&ohrcigr;" p "&#x1fa7;"    % "<=w|"
"&OHrcigr;" p "&#x1faf;"    % "<=W|"
"&ohscigr;" p "&#x1fa6;"    % ">=w|"
"&OHscigr;" p "&#x1fae;"    % ">=W|"
"&ohrougr;" p "&#x1f61;"    % "<w"
"&OHrougr;" p "&#x1f69;"    % "<W"
"&ohsmogr;" p "&#x1f60;"    % ">w"
"&OHsmogr;" p "&#x1f68;"    % ">W"
"&ohgragr;" p "&#x1f7c;"    % "`w"
"&OHgragr;" p "&#x1ffa;"    % "`W"
"&ohacugr;" p "&#x1f7d;"    % "'w"
"&OHacugr;" p "&#x1ffb;"    % "'W"
"&ohcirgr;" p "&#x1ff6;"    % "=w"
"&OHcirgr;" p "&#x3a9;&#x342;"  % "=W"
"&ohragr;"  p "&#x1f65;"    % "<'w"
"&OHragr;"  p "&#x1f6d;"    % "<'W"
"&ohsagr;"  p "&#x1f64;"    % ">'w"
"&OHsagr;"  p "&#x1f6c;"    % ">'W"
"&ohrggr;"  p "&#x1f63;"    % "<`w"
"&OHrggr;"  p "&#x1f6b;"    % "<`W"
"&ohsggr;"  p "&#x1f62;"    % ">`w"
"&OHsggr;"  p "&#x1f6a;"    % ">`W"
"&ohrcgr;"  p "&#x1f67;"    % "<=w"
"&OHrcgr;"  p "&#x1f6f;"    % "<=W"
"&ohscgr;"  p "&#x1f66;"    % ">=w"
"&OHscgr;"  p "&#x1f6e;"    % ">=W"

% punctuation marks

"&ckgr;"    p "&#x387;"     % "&middot;"
"&qmgr;"    p "&#x37e;"     % ";"

"&apos;"    p "&#x2bc;"     % "&apos;"
"&prime;"   p "&#x2032;"    % "&prime;"

%% additional entities not in TEI

"&amacgr;"  p "&#x3b1;&#x304;"  % "\\=a"
"&Amacgr;"  p "&#x391;&#x304;"  % "\\=A"
"&abregr;"  p "&#x3b1;&#x306;"  % ")a"
"&Abregr;"  p "&#x391;&#x306;"  % ")A"

