
    # ASCII

    $ent{'excl'}        = chr(0x0021);  #  EXCLAMATION MARK
    $ent{'quot'}        = chr(0x0022);  #  QUOTATION MARK
    $ent{'num'}         = chr(0x0023);  #  NUMBER SIGN
    $ent{'dollar'}      = chr(0x0024);  #  DOLLAR SIGN
    $ent{'percnt'}      = chr(0x0025);  #  PERCENT SIGN
    $ent{'amp'}         = chr(0x0026);  #  AMPERSAND
    $ent{'lpar'}        = chr(0x0028);  #  LEFT PARENTHESIS
    $ent{'rpar'}        = chr(0x0029);  #  RIGHT PARENTHESIS
    $ent{'ast'}         = chr(0x002A);  #  ASTERISK
    $ent{'plus'}        = chr(0x002B);  #  PLUS SIGN
    $ent{'comma'}       = chr(0x002C);  #  COMMA
    $ent{'hyphen'}      = chr(0x002D);  #  HYPHEN-MINUS
    $ent{'period'}      = chr(0x002E);  #  FULL STOP
    $ent{'sol'}         = chr(0x002F);  #  SOLIDUS
    $ent{'colon'}       = chr(0x003A);  #  COLON
    $ent{'semi'}        = chr(0x003B);  #  SEMICOLON
    $ent{'lt'}          = chr(0x003C);  #  LESS-THAN SIGN
    $ent{'equals'}      = chr(0x003D);  #  EQUALS SIGN
    $ent{'gt'}          = chr(0x003E);  #  GREATER-THAN SIGN
    $ent{'quest'}       = chr(0x003F);  #  QUESTION MARK
    $ent{'commat'}      = chr(0x0040);  #  COMMERCIAL AT
    $ent{'lsqb'}        = chr(0x005B);  #  LEFT SQUARE BRACKET
    $ent{'bsol'}        = chr(0x005C);  #  REVERSE SOLIDUS
    $ent{'rsqb'}        = chr(0x005D);  #  RIGHT SQUARE BRACKET
    $ent{'lowbar'}      = chr(0x005F);  #  LOW LINE
    $ent{'grave'}       = chr(0x0060);  #  GRAVE ACCENT
    $ent{'lcub'}        = chr(0x007B);  #  LEFT CURLY BRACKET
    $ent{'verbar'}      = chr(0x007C);  #  VERTICAL LINE
    $ent{'rcub'}        = chr(0x007D);  #  RIGHT CURLY BRACKET


    $ent{'nbsp'}        = chr(0x00A0);  #  NO-BREAK SPACE
    $ent{'iexcl'}       = chr(0x00A1);  #  INVERTED EXCLAMATION MARK
    $ent{'cent'}        = chr(0x00A2);  #  CENT SIGN
    $ent{'pound'}       = chr(0x00A3);  #  POUND SIGN
    $ent{'curren'}      = chr(0x00A4);  #  CURRENCY SIGN
    $ent{'yen'}         = chr(0x00A5);  #  YEN SIGN
    $ent{'brvbar'}      = chr(0x00A6);  #  BROKEN BAR
    $ent{'sect'}        = chr(0x00A7);  #  SECTION SIGN
    $ent{'uml'}         = chr(0x00A8);  #  DIAERESIS
    $ent{'copy'}        = chr(0x00A9);  #  COPYRIGHT SIGN
    $ent{'ordf'}        = chr(0x00AA);  #  FEMININE ORDINAL INDICATOR
    $ent{'laquo'}       = chr(0x00AB);  #  LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
    $ent{'not'}         = chr(0x00AC);  #  NOT SIGN
    $ent{'shy'}         = chr(0x00AD);  #  SOFT HYPHEN
    $ent{'reg'}         = chr(0x00AE);  #  REGISTERED SIGN
    $ent{'macr'}        = chr(0x00AF);  #  MACRON
    $ent{'deg'}         = chr(0x00B0);  #  DEGREE SIGN
    $ent{'plusmn'}      = chr(0x00B1);  #  PLUS-MINUS SIGN
    $ent{'sup2'}        = chr(0x00B2);  #  SUPERSCRIPT TWO
    $ent{'sup3'}        = chr(0x00B3);  #  SUPERSCRIPT THREE
    $ent{'acute'}       = chr(0x00B4);  #  ACUTE ACCENT
    $ent{'micro'}       = chr(0x00B5);  #  MICRO SIGN
    $ent{'para'}        = chr(0x00B6);  #  PILCROW SIGN
    $ent{'middot'}      = chr(0x00B7);  #  MIDDLE DOT
    $ent{'cedil'}       = chr(0x00B8);  #  CEDILLA
    $ent{'sup1'}        = chr(0x00B9);  #  SUPERSCRIPT ONE
    $ent{'ordm'}        = chr(0x00BA);  #  MASCULINE ORDINAL INDICATOR
    $ent{'raquo'}       = chr(0x00BB);  #  RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
    $ent{'frac14'}      = chr(0x00BC);  #  VULGAR FRACTION ONE QUARTER
    $ent{'frac12'}      = chr(0x00BD);  #  VULGAR FRACTION ONE HALF
    $ent{'frac34'}      = chr(0x00BE);  #  VULGAR FRACTION THREE QUARTERS
    $ent{'iquest'}      = chr(0x00BF);  #  INVERTED QUESTION MARK
    $ent{'Agrave'}      = chr(0x00C0);  #  LATIN CAPITAL LETTER A WITH GRAVE
    $ent{'Aacute'}      = chr(0x00C1);  #  LATIN CAPITAL LETTER A WITH ACUTE
    $ent{'Acirc'}       = chr(0x00C2);  #  LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    $ent{'Atilde'}      = chr(0x00C3);  #  LATIN CAPITAL LETTER A WITH TILDE
    $ent{'Auml'}        = chr(0x00C4);  #  LATIN CAPITAL LETTER A WITH DIAERESIS
    $ent{'Aring'}       = chr(0x00C5);  #  LATIN CAPITAL LETTER A WITH RING ABOVE
    $ent{'AElig'}       = chr(0x00C6);  #  LATIN CAPITAL LETTER AE
    $ent{'Ccedil'}      = chr(0x00C7);  #  LATIN CAPITAL LETTER C WITH CEDILLA
    $ent{'Egrave'}      = chr(0x00C8);  #  LATIN CAPITAL LETTER E WITH GRAVE
    $ent{'Eacute'}      = chr(0x00C9);  #  LATIN CAPITAL LETTER E WITH ACUTE
    $ent{'Ecirc'}       = chr(0x00CA);  #  LATIN CAPITAL LETTER E WITH CIRCUMFLEX
    $ent{'Euml'}        = chr(0x00CB);  #  LATIN CAPITAL LETTER E WITH DIAERESIS
    $ent{'Igrave'}      = chr(0x00CC);  #  LATIN CAPITAL LETTER I WITH GRAVE
    $ent{'Iacute'}      = chr(0x00CD);  #  LATIN CAPITAL LETTER I WITH ACUTE
    $ent{'Icirc'}       = chr(0x00CE);  #  LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    $ent{'Iuml'}        = chr(0x00CF);  #  LATIN CAPITAL LETTER I WITH DIAERESIS
    $ent{'ETH'}         = chr(0x00D0);  #  LATIN CAPITAL LETTER ETH
    $ent{'Ntilde'}      = chr(0x00D1);  #  LATIN CAPITAL LETTER N WITH TILDE
    $ent{'Ograve'}      = chr(0x00D2);  #  LATIN CAPITAL LETTER O WITH GRAVE
    $ent{'Oacute'}      = chr(0x00D3);  #  LATIN CAPITAL LETTER O WITH ACUTE
    $ent{'Ocirc'}       = chr(0x00D4);  #  LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    $ent{'Otilde'}      = chr(0x00D5);  #  LATIN CAPITAL LETTER O WITH TILDE
    $ent{'Ouml'}        = chr(0x00D6);  #  LATIN CAPITAL LETTER O WITH DIAERESIS
    $ent{'times'}       = chr(0x00D7);  #  MULTIPLICATION SIGN
    $ent{'Oslash'}      = chr(0x00D8);  #  LATIN CAPITAL LETTER O WITH STROKE
    $ent{'Ugrave'}      = chr(0x00D9);  #  LATIN CAPITAL LETTER U WITH GRAVE
    $ent{'Uacute'}      = chr(0x00DA);  #  LATIN CAPITAL LETTER U WITH ACUTE
    $ent{'Ucirc'}       = chr(0x00DB);  #  LATIN CAPITAL LETTER U WITH CIRCUMFLEX
    $ent{'Uuml'}        = chr(0x00DC);  #  LATIN CAPITAL LETTER U WITH DIAERESIS
    $ent{'Yacute'}      = chr(0x00DD);  #  LATIN CAPITAL LETTER Y WITH ACUTE
    $ent{'THORN'}       = chr(0x00DE);  #  LATIN CAPITAL LETTER THORN
    $ent{'szlig'}       = chr(0x00DF);  #  LATIN SMALL LETTER SHARP S
    $ent{'agrave'}      = chr(0x00E0);  #  LATIN SMALL LETTER A WITH GRAVE
    $ent{'aacute'}      = chr(0x00E1);  #  LATIN SMALL LETTER A WITH ACUTE
    $ent{'acirc'}       = chr(0x00E2);  #  LATIN SMALL LETTER A WITH CIRCUMFLEX
    $ent{'atilde'}      = chr(0x00E3);  #  LATIN SMALL LETTER A WITH TILDE
    $ent{'auml'}        = chr(0x00E4);  #  LATIN SMALL LETTER A WITH DIAERESIS
    $ent{'aring'}       = chr(0x00E5);  #  LATIN SMALL LETTER A WITH RING ABOVE
    $ent{'aelig'}       = chr(0x00E6);  #  LATIN SMALL LETTER AE
    $ent{'ccedil'}      = chr(0x00E7);  #  LATIN SMALL LETTER C WITH CEDILLA
    $ent{'egrave'}      = chr(0x00E8);  #  LATIN SMALL LETTER E WITH GRAVE
    $ent{'eacute'}      = chr(0x00E9);  #  LATIN SMALL LETTER E WITH ACUTE
    $ent{'ecirc'}       = chr(0x00EA);  #  LATIN SMALL LETTER E WITH CIRCUMFLEX
    $ent{'euml'}        = chr(0x00EB);  #  LATIN SMALL LETTER E WITH DIAERESIS
    $ent{'igrave'}      = chr(0x00EC);  #  LATIN SMALL LETTER I WITH GRAVE
    $ent{'iacute'}      = chr(0x00ED);  #  LATIN SMALL LETTER I WITH ACUTE
    $ent{'icirc'}       = chr(0x00EE);  #  LATIN SMALL LETTER I WITH CIRCUMFLEX
    $ent{'iuml'}        = chr(0x00EF);  #  LATIN SMALL LETTER I WITH DIAERESIS
    $ent{'eth'}         = chr(0x00F0);  #  LATIN SMALL LETTER ETH
    $ent{'ntilde'}      = chr(0x00F1);  #  LATIN SMALL LETTER N WITH TILDE
    $ent{'ograve'}      = chr(0x00F2);  #  LATIN SMALL LETTER O WITH GRAVE
    $ent{'oacute'}      = chr(0x00F3);  #  LATIN SMALL LETTER O WITH ACUTE
    $ent{'ocirc'}       = chr(0x00F4);  #  LATIN SMALL LETTER O WITH CIRCUMFLEX
    $ent{'otilde'}      = chr(0x00F5);  #  LATIN SMALL LETTER O WITH TILDE
    $ent{'ouml'}        = chr(0x00F6);  #  LATIN SMALL LETTER O WITH DIAERESIS
    $ent{'divide'}      = chr(0x00F7);  #  DIVISION SIGN
    $ent{'oslash'}      = chr(0x00F8);  #  LATIN SMALL LETTER O WITH STROKE
    $ent{'ugrave'}      = chr(0x00F9);  #  LATIN SMALL LETTER U WITH GRAVE
    $ent{'uacute'}      = chr(0x00FA);  #  LATIN SMALL LETTER U WITH ACUTE
    $ent{'ucirc'}       = chr(0x00FB);  #  LATIN SMALL LETTER U WITH CIRCUMFLEX
    $ent{'uuml'}        = chr(0x00FC);  #  LATIN SMALL LETTER U WITH DIAERESIS
    $ent{'yacute'}      = chr(0x00FD);  #  LATIN SMALL LETTER Y WITH ACUTE
    $ent{'thorn'}       = chr(0x00FE);  #  LATIN SMALL LETTER THORN
    $ent{'yuml'}        = chr(0x00FF);  #  LATIN SMALL LETTER Y WITH DIAERESIS


    $ent{'Amacr'}       = chr(0x0100);  #  LATIN CAPITAL LETTER A WITH MACRON
    $ent{'amacr'}       = chr(0x0101);  #  LATIN SMALL LETTER A WITH MACRON
    $ent{'Abreve'}      = chr(0x0102);  #  LATIN CAPITAL LETTER A WITH BREVE
    $ent{'abreve'}      = chr(0x0103);  #  LATIN SMALL LETTER A WITH BREVE
    $ent{'Aogon'}       = chr(0x0104);  #  LATIN CAPITAL LETTER A WITH OGONEK
    $ent{'aogon'}       = chr(0x0105);  #  LATIN SMALL LETTER A WITH OGONEK
    $ent{'Cacute'}      = chr(0x0106);  #  LATIN CAPITAL LETTER C WITH ACUTE
    $ent{'cacute'}      = chr(0x0107);  #  LATIN SMALL LETTER C WITH ACUTE
    $ent{'Ccirc'}       = chr(0x0108);  #  LATIN CAPITAL LETTER C WITH CIRCUMFLEX
    $ent{'ccirc'}       = chr(0x0109);  #  LATIN SMALL LETTER C WITH CIRCUMFLEX
    $ent{'Cdot'}        = chr(0x010A);  #  LATIN CAPITAL LETTER C WITH DOT ABOVE
    $ent{'cdot'}        = chr(0x010B);  #  LATIN SMALL LETTER C WITH DOT ABOVE
    $ent{'Ccaron'}      = chr(0x010C);  #  LATIN CAPITAL LETTER C WITH CARON
    $ent{'ccaron'}      = chr(0x010D);  #  LATIN SMALL LETTER C WITH CARON
    $ent{'Dcaron'}      = chr(0x010E);  #  LATIN CAPITAL LETTER D WITH CARON
    $ent{'dcaron'}      = chr(0x010F);  #  LATIN SMALL LETTER D WITH CARON
    $ent{'Dstrok'}      = chr(0x0110);  #  LATIN CAPITAL LETTER D WITH STROKE
    $ent{'dstrok'}      = chr(0x0111);  #  LATIN SMALL LETTER D WITH STROKE
    $ent{'Emacr'}       = chr(0x0112);  #  LATIN CAPITAL LETTER E WITH MACRON
    $ent{'emacr'}       = chr(0x0113);  #  LATIN SMALL LETTER E WITH MACRON
    $ent{'Edot'}        = chr(0x0116);  #  LATIN CAPITAL LETTER E WITH DOT ABOVE
    $ent{'edot'}        = chr(0x0117);  #  LATIN SMALL LETTER E WITH DOT ABOVE
    $ent{'Eogon'}       = chr(0x0118);  #  LATIN CAPITAL LETTER E WITH OGONEK
    $ent{'eogon'}       = chr(0x0119);  #  LATIN SMALL LETTER E WITH OGONEK
    $ent{'Ecaron'}      = chr(0x011A);  #  LATIN CAPITAL LETTER E WITH CARON
    $ent{'ecaron'}      = chr(0x011B);  #  LATIN SMALL LETTER E WITH CARON
    $ent{'Gcirc'}       = chr(0x011C);  #  LATIN CAPITAL LETTER G WITH CIRCUMFLEX
    $ent{'gcirc'}       = chr(0x011D);  #  LATIN SMALL LETTER G WITH CIRCUMFLEX
    $ent{'Gbreve'}      = chr(0x011E);  #  LATIN CAPITAL LETTER G WITH BREVE
    $ent{'gbreve'}      = chr(0x011F);  #  LATIN SMALL LETTER G WITH BREVE
    $ent{'Gdot'}        = chr(0x0120);  #  LATIN CAPITAL LETTER G WITH DOT ABOVE
    $ent{'gdot'}        = chr(0x0121);  #  LATIN SMALL LETTER G WITH DOT ABOVE
    $ent{'Gcedil'}      = chr(0x0122);  #  LATIN CAPITAL LETTER G WITH CEDILLA
    $ent{'gcedil'}      = chr(0x0123);  #  LATIN SMALL LETTER G WITH CEDILLA
    $ent{'Hcirc'}       = chr(0x0124);  #  LATIN CAPITAL LETTER H WITH CIRCUMFLEX
    $ent{'hcirc'}       = chr(0x0125);  #  LATIN SMALL LETTER H WITH CIRCUMFLEX
    $ent{'Hstrok'}      = chr(0x0126);  #  LATIN CAPITAL LETTER H WITH STROKE
    $ent{'hstrok'}      = chr(0x0127);  #  LATIN SMALL LETTER H WITH STROKE
    $ent{'Itilde'}      = chr(0x0128);  #  LATIN CAPITAL LETTER I WITH TILDE
    $ent{'itilde'}      = chr(0x0129);  #  LATIN SMALL LETTER I WITH TILDE
    $ent{'Imacr'}       = chr(0x012A);  #  LATIN CAPITAL LETTER I WITH MACRON
    $ent{'imacr'}       = chr(0x012B);  #  LATIN SMALL LETTER I WITH MACRON
    $ent{'Iogon'}       = chr(0x012E);  #  LATIN CAPITAL LETTER I WITH OGONEK
    $ent{'iogon'}       = chr(0x012F);  #  LATIN SMALL LETTER I WITH OGONEK
    $ent{'Idot'}        = chr(0x0130);  #  LATIN CAPITAL LETTER I WITH DOT ABOVE
    $ent{'inodot'}      = chr(0x0131);  #  LATIN SMALL LETTER DOTLESS I
    $ent{'IJlig'}       = chr(0x0132);  #  LATIN CAPITAL LIGATURE IJ
    $ent{'ijlig'}       = chr(0x0133);  #  LATIN SMALL LIGATURE IJ
    $ent{'Jcirc'}       = chr(0x0134);  #  LATIN CAPITAL LETTER J WITH CIRCUMFLEX
    $ent{'jcirc'}       = chr(0x0135);  #  LATIN SMALL LETTER J WITH CIRCUMFLEX
    $ent{'Kcedil'}      = chr(0x0136);  #  LATIN CAPITAL LETTER K WITH CEDILLA
    $ent{'kcedil'}      = chr(0x0137);  #  LATIN SMALL LETTER K WITH CEDILLA
    $ent{'kgreen'}      = chr(0x0138);  #  LATIN SMALL LETTER KRA
    $ent{'Lacute'}      = chr(0x0139);  #  LATIN CAPITAL LETTER L WITH ACUTE
    $ent{'lacute'}      = chr(0x013A);  #  LATIN SMALL LETTER L WITH ACUTE
    $ent{'Lcedil'}      = chr(0x013B);  #  LATIN CAPITAL LETTER L WITH CEDILLA
    $ent{'lcedil'}      = chr(0x013C);  #  LATIN SMALL LETTER L WITH CEDILLA
    $ent{'Lcaron'}      = chr(0x013D);  #  LATIN CAPITAL LETTER L WITH CARON
    $ent{'lcaron'}      = chr(0x013E);  #  LATIN SMALL LETTER L WITH CARON
    $ent{'Lmidot'}      = chr(0x013F);  #  LATIN CAPITAL LETTER L WITH MIDDLE DOT
    $ent{'lmidot'}      = chr(0x0140);  #  LATIN SMALL LETTER L WITH MIDDLE DOT
    $ent{'Lstrok'}      = chr(0x0141);  #  LATIN CAPITAL LETTER L WITH STROKE
    $ent{'lstrok'}      = chr(0x0142);  #  LATIN SMALL LETTER L WITH STROKE
    $ent{'Nacute'}      = chr(0x0143);  #  LATIN CAPITAL LETTER N WITH ACUTE
    $ent{'nacute'}      = chr(0x0144);  #  LATIN SMALL LETTER N WITH ACUTE
    $ent{'Ncedil'}      = chr(0x0145);  #  LATIN CAPITAL LETTER N WITH CEDILLA
    $ent{'ncedil'}      = chr(0x0146);  #  LATIN SMALL LETTER N WITH CEDILLA
    $ent{'Ncaron'}      = chr(0x0147);  #  LATIN CAPITAL LETTER N WITH CARON
    $ent{'ncaron'}      = chr(0x0148);  #  LATIN SMALL LETTER N WITH CARON
    $ent{'napos'}       = chr(0x0149);  #  LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
    $ent{'ENG'}         = chr(0x014A);  #  LATIN CAPITAL LETTER ENG
    $ent{'eng'}         = chr(0x014B);  #  LATIN SMALL LETTER ENG
    $ent{'Omacr'}       = chr(0x014C);  #  LATIN CAPITAL LETTER O WITH MACRON
    $ent{'omacr'}       = chr(0x014D);  #  LATIN SMALL LETTER O WITH MACRON
    $ent{'Odblac'}      = chr(0x0150);  #  LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    $ent{'odblac'}      = chr(0x0151);  #  LATIN SMALL LETTER O WITH DOUBLE ACUTE
    $ent{'OElig'}       = chr(0x0152);  #  LATIN CAPITAL LIGATURE OE
    $ent{'oelig'}       = chr(0x0153);  #  LATIN SMALL LIGATURE OE
    $ent{'Racute'}      = chr(0x0154);  #  LATIN CAPITAL LETTER R WITH ACUTE
    $ent{'racute'}      = chr(0x0155);  #  LATIN SMALL LETTER R WITH ACUTE
    $ent{'Rcedil'}      = chr(0x0156);  #  LATIN CAPITAL LETTER R WITH CEDILLA
    $ent{'rcedil'}      = chr(0x0157);  #  LATIN SMALL LETTER R WITH CEDILLA
    $ent{'Rcaron'}      = chr(0x0158);  #  LATIN CAPITAL LETTER R WITH CARON
    $ent{'rcaron'}      = chr(0x0159);  #  LATIN SMALL LETTER R WITH CARON
    $ent{'Sacute'}      = chr(0x015A);  #  LATIN CAPITAL LETTER S WITH ACUTE
    $ent{'sacute'}      = chr(0x015B);  #  LATIN SMALL LETTER S WITH ACUTE
    $ent{'Scirc'}       = chr(0x015C);  #  LATIN CAPITAL LETTER S WITH CIRCUMFLEX
    $ent{'scirc'}       = chr(0x015D);  #  LATIN SMALL LETTER S WITH CIRCUMFLEX
    $ent{'Scedil'}      = chr(0x015E);  #  LATIN CAPITAL LETTER S WITH CEDILLA
    $ent{'scedil'}      = chr(0x015F);  #  LATIN SMALL LETTER S WITH CEDILLA
    $ent{'Scaron'}      = chr(0x0160);  #  LATIN CAPITAL LETTER S WITH CARON
    $ent{'scaron'}      = chr(0x0161);  #  LATIN SMALL LETTER S WITH CARON
    $ent{'Tcedil'}      = chr(0x0162);  #  LATIN CAPITAL LETTER T WITH CEDILLA
    $ent{'tcedil'}      = chr(0x0163);  #  LATIN SMALL LETTER T WITH CEDILLA
    $ent{'Tcaron'}      = chr(0x0164);  #  LATIN CAPITAL LETTER T WITH CARON
    $ent{'tcaron'}      = chr(0x0165);  #  LATIN SMALL LETTER T WITH CARON
    $ent{'Tstrok'}      = chr(0x0166);  #  LATIN CAPITAL LETTER T WITH STROKE
    $ent{'tstrok'}      = chr(0x0167);  #  LATIN SMALL LETTER T WITH STROKE
    $ent{'Utilde'}      = chr(0x0168);  #  LATIN CAPITAL LETTER U WITH TILDE
    $ent{'utilde'}      = chr(0x0169);  #  LATIN SMALL LETTER U WITH TILDE
    $ent{'Umacr'}       = chr(0x016A);  #  LATIN CAPITAL LETTER U WITH MACRON
    $ent{'umacr'}       = chr(0x016B);  #  LATIN SMALL LETTER U WITH MACRON
    $ent{'Ubreve'}      = chr(0x016C);  #  LATIN CAPITAL LETTER U WITH BREVE
    $ent{'ubreve'}      = chr(0x016D);  #  LATIN SMALL LETTER U WITH BREVE
    $ent{'Uring'}       = chr(0x016E);  #  LATIN CAPITAL LETTER U WITH RING ABOVE
    $ent{'uring'}       = chr(0x016F);  #  LATIN SMALL LETTER U WITH RING ABOVE
    $ent{'Udblac'}      = chr(0x0170);  #  LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    $ent{'udblac'}      = chr(0x0171);  #  LATIN SMALL LETTER U WITH DOUBLE ACUTE
    $ent{'Uogon'}       = chr(0x0172);  #  LATIN CAPITAL LETTER U WITH OGONEK
    $ent{'uogon'}       = chr(0x0173);  #  LATIN SMALL LETTER U WITH OGONEK
    $ent{'Wcirc'}       = chr(0x0174);  #  LATIN CAPITAL LETTER W WITH CIRCUMFLEX
    $ent{'wcirc'}       = chr(0x0175);  #  LATIN SMALL LETTER W WITH CIRCUMFLEX
    $ent{'Ycirc'}       = chr(0x0176);  #  LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
    $ent{'ycirc'}       = chr(0x0177);  #  LATIN SMALL LETTER Y WITH CIRCUMFLEX
    $ent{'Yuml'}        = chr(0x0178);  #  LATIN CAPITAL LETTER Y WITH DIAERESIS
    $ent{'Zacute'}      = chr(0x0179);  #  LATIN CAPITAL LETTER Z WITH ACUTE
    $ent{'zacute'}      = chr(0x017A);  #  LATIN SMALL LETTER Z WITH ACUTE
    $ent{'Zdot'}        = chr(0x017B);  #  LATIN CAPITAL LETTER Z WITH DOT ABOVE
    $ent{'zdot'}        = chr(0x017C);  #  LATIN SMALL LETTER Z WITH DOT ABOVE
    $ent{'Zcaron'}      = chr(0x017D);  #  LATIN CAPITAL LETTER Z WITH CARON
    $ent{'zcaron'}      = chr(0x017E);  #  LATIN SMALL LETTER Z WITH CARON
    $ent{'fnof'}        = chr(0x0192);  #  LATIN SMALL LETTER F WITH HOOK
    $ent{'Ohorn'}       = chr(0x01A0);  #  LATIN CAPITAL LETTER O WITH HORN
    $ent{'ohorn'}       = chr(0x01A1);  #  LATIN SMALL LETTER O WITH HORN
    $ent{'Uhorn'}       = chr(0x01AF);  #  LATIN CAPITAL LETTER U WITH HORN
    $ent{'uhorn'}       = chr(0x01B0);  #  LATIN SMALL LETTER U WITH HORN
    $ent{'dclick'}      = chr(0x01C0);  #  LATIN LETTER DENTAL CLICK
    $ent{'lclick'}      = chr(0x01C1);  #  LATIN LETTER LATERAL CLICK
    $ent{'aclick'}      = chr(0x01C2);  #  LATIN LETTER ALVEOLAR CLICK
    $ent{'rclick'}      = chr(0x01C3);  #  LATIN LETTER RETROFLEX CLICK
    $ent{'gacute'}      = chr(0x01F5);  #  LATIN SMALL LETTER G WITH ACUTE


    $ent{'mlapos'}      = chr(0x02BC);  #  MODIFIER LETTER APOSTROPHE
    $ent{'circ'}        = chr(0x02C6);  #  MODIFIER LETTER CIRCUMFLEX ACCENT
    $ent{'caron'}       = chr(0x02C7);  #  CARON
    $ent{'breve'}       = chr(0x02D8);  #  BREVE
    $ent{'dot'}         = chr(0x02D9);  #  DOT ABOVE
    $ent{'ring'}        = chr(0x02DA);  #  RING ABOVE
    $ent{'ogon'}        = chr(0x02DB);  #  OGONEK
    $ent{'tilde'}       = chr(0x02DC);  #  SMALL TILDE
    $ent{'dblac'}       = chr(0x02DD);  #  DOUBLE ACUTE ACCENT


    $ent{'Aacgr'}       = chr(0x0386);  #  GREEK CAPITAL LETTER ALPHA WITH TONOS
    $ent{'Eacgr'}       = chr(0x0388);  #  GREEK CAPITAL LETTER EPSILON WITH TONOS
    $ent{'EEacgr'}      = chr(0x0389);  #  GREEK CAPITAL LETTER ETA WITH TONOS
    $ent{'Iacgr'}       = chr(0x038A);  #  GREEK CAPITAL LETTER IOTA WITH TONOS
    $ent{'Oacgr'}       = chr(0x038C);  #  GREEK CAPITAL LETTER OMICRON WITH TONOS
    $ent{'Uacgr'}       = chr(0x038E);  #  GREEK CAPITAL LETTER UPSILON WITH TONOS
    $ent{'OHacgr'}      = chr(0x038F);  #  GREEK CAPITAL LETTER OMEGA WITH TONOS
    $ent{'idiagr'}      = chr(0x0390);  #  GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
    $ent{'Agr'}         = chr(0x0391);  #  GREEK CAPITAL LETTER ALPHA
    $ent{'Bgr'}         = chr(0x0392);  #  GREEK CAPITAL LETTER BETA
    $ent{'Ggr'}         = chr(0x0393);  #  GREEK CAPITAL LETTER GAMMA
    $ent{'Dgr'}         = chr(0x0394);  #  GREEK CAPITAL LETTER DELTA
    $ent{'Egr'}         = chr(0x0395);  #  GREEK CAPITAL LETTER EPSILON
    $ent{'Zgr'}         = chr(0x0396);  #  GREEK CAPITAL LETTER ZETA
    $ent{'EEgr'}        = chr(0x0397);  #  GREEK CAPITAL LETTER ETA
    $ent{'THgr'}        = chr(0x0398);  #  GREEK CAPITAL LETTER THETA
    $ent{'Igr'}         = chr(0x0399);  #  GREEK CAPITAL LETTER IOTA
    $ent{'Kgr'}         = chr(0x039A);  #  GREEK CAPITAL LETTER KAPPA
    $ent{'Lgr'}         = chr(0x039B);  #  GREEK CAPITAL LETTER LAMDA
    $ent{'Mgr'}         = chr(0x039C);  #  GREEK CAPITAL LETTER MU
    $ent{'Ngr'}         = chr(0x039D);  #  GREEK CAPITAL LETTER NU
    $ent{'Xgr'}         = chr(0x039E);  #  GREEK CAPITAL LETTER XI
    $ent{'Ogr'}         = chr(0x039F);  #  GREEK CAPITAL LETTER OMICRON
    $ent{'Pgr'}         = chr(0x03A0);  #  GREEK CAPITAL LETTER PI
    $ent{'Rgr'}         = chr(0x03A1);  #  GREEK CAPITAL LETTER RHO
    $ent{'Sgr'}         = chr(0x03A3);  #  GREEK CAPITAL LETTER SIGMA
    $ent{'Tgr'}         = chr(0x03A4);  #  GREEK CAPITAL LETTER TAU
    $ent{'Ugr'}         = chr(0x03A5);  #  GREEK CAPITAL LETTER UPSILON
    $ent{'PHgr'}        = chr(0x03A6);  #  GREEK CAPITAL LETTER PHI
    $ent{'KHgr'}        = chr(0x03A7);  #  GREEK CAPITAL LETTER CHI
    $ent{'PSgr'}        = chr(0x03A8);  #  GREEK CAPITAL LETTER PSI
    $ent{'OHgr'}        = chr(0x03A9);  #  GREEK CAPITAL LETTER OMEGA
    $ent{'Idigr'}       = chr(0x03AA);  #  GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
    $ent{'Udigr'}       = chr(0x03AB);  #  GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
    $ent{'aacgr'}       = chr(0x03AC);  #  GREEK SMALL LETTER ALPHA WITH TONOS
    $ent{'eacgr'}       = chr(0x03AD);  #  GREEK SMALL LETTER EPSILON WITH TONOS
    $ent{'eeacgr'}      = chr(0x03AE);  #  GREEK SMALL LETTER ETA WITH TONOS
    $ent{'iacgr'}       = chr(0x03AF);  #  GREEK SMALL LETTER IOTA WITH TONOS
    $ent{'udiagr'}      = chr(0x03B0);  #  GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND
    $ent{'agr'}         = chr(0x03B1);  #  GREEK SMALL LETTER ALPHA
    $ent{'bgr'}         = chr(0x03B2);  #  GREEK SMALL LETTER BETA
    $ent{'ggr'}         = chr(0x03B3);  #  GREEK SMALL LETTER GAMMA
    $ent{'dgr'}         = chr(0x03B4);  #  GREEK SMALL LETTER DELTA
    $ent{'egr'}         = chr(0x03B5);  #  GREEK SMALL LETTER EPSILON
    $ent{'zgr'}         = chr(0x03B6);  #  GREEK SMALL LETTER ZETA
    $ent{'eegr'}        = chr(0x03B7);  #  GREEK SMALL LETTER ETA
    $ent{'thgr'}        = chr(0x03B8);  #  GREEK SMALL LETTER THETA
    $ent{'igr'}         = chr(0x03B9);  #  GREEK SMALL LETTER IOTA
    $ent{'kgr'}         = chr(0x03BA);  #  GREEK SMALL LETTER KAPPA
    $ent{'lgr'}         = chr(0x03BB);  #  GREEK SMALL LETTER LAMDA
    $ent{'mgr'}         = chr(0x03BC);  #  GREEK SMALL LETTER MU
    $ent{'ngr'}         = chr(0x03BD);  #  GREEK SMALL LETTER NU
    $ent{'xgr'}         = chr(0x03BE);  #  GREEK SMALL LETTER XI
    $ent{'ogr'}         = chr(0x03BF);  #  GREEK SMALL LETTER OMICRON
    $ent{'pgr'}         = chr(0x03C0);  #  GREEK SMALL LETTER PI
    $ent{'rgr'}         = chr(0x03C1);  #  GREEK SMALL LETTER RHO
    $ent{'sfgr'}        = chr(0x03C2);  #  GREEK SMALL LETTER FINAL SIGMA
    $ent{'sgr'}         = chr(0x03C3);  #  GREEK SMALL LETTER SIGMA
    $ent{'tgr'}         = chr(0x03C4);  #  GREEK SMALL LETTER TAU
    $ent{'ugr'}         = chr(0x03C5);  #  GREEK SMALL LETTER UPSILON
    $ent{'phgr'}        = chr(0x03C6);  #  GREEK SMALL LETTER PHI
    $ent{'khgr'}        = chr(0x03C7);  #  GREEK SMALL LETTER CHI
    $ent{'psgr'}        = chr(0x03C8);  #  GREEK SMALL LETTER PSI
    $ent{'ohgr'}        = chr(0x03C9);  #  GREEK SMALL LETTER OMEGA
    $ent{'idigr'}       = chr(0x03CA);  #  GREEK SMALL LETTER IOTA WITH DIALYTIKA
    $ent{'udigr'}       = chr(0x03CB);  #  GREEK SMALL LETTER UPSILON WITH DIALYTIKA
    $ent{'oacgr'}       = chr(0x03CC);  #  GREEK SMALL LETTER OMICRON WITH TONOS
    $ent{'uacgr'}       = chr(0x03CD);  #  GREEK SMALL LETTER UPSILON WITH TONOS
    $ent{'ohacgr'}      = chr(0x03CE);  #  GREEK SMALL LETTER OMEGA WITH TONOS
    $ent{'thetasym'}    = chr(0x03D1);  #  GREEK THETA SYMBOL
    $ent{'upsih'}       = chr(0x03D2);  #  GREEK UPSILON WITH HOOK SYMBOL
    $ent{'phiv'}        = chr(0x03D5);  #  GREEK PHI SYMBOL
    $ent{'piv'}         = chr(0x03D6);  #  GREEK PI SYMBOL
    $ent{'kappav'}      = chr(0x03F0);  #  GREEK KAPPA SYMBOL
    $ent{'rhov'}        = chr(0x03F1);  #  GREEK RHO SYMBOL


    $ent{'IOcy'}        = chr(0x0401);  #  CYRILLIC CAPITAL LETTER IO
    $ent{'DJcy'}        = chr(0x0402);  #  CYRILLIC CAPITAL LETTER DJE
    $ent{'GJcy'}        = chr(0x0403);  #  CYRILLIC CAPITAL LETTER GJE
    $ent{'Jukcy'}       = chr(0x0404);  #  CYRILLIC CAPITAL LETTER UKRAINIAN IE
    $ent{'DScy'}        = chr(0x0405);  #  CYRILLIC CAPITAL LETTER DZE
    $ent{'Iukcy'}       = chr(0x0406);  #  CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
    $ent{'YIcy'}        = chr(0x0407);  #  CYRILLIC CAPITAL LETTER YI
    $ent{'Jsercy'}      = chr(0x0408);  #  CYRILLIC CAPITAL LETTER JE
    $ent{'LJcy'}        = chr(0x0409);  #  CYRILLIC CAPITAL LETTER LJE
    $ent{'NJcy'}        = chr(0x040A);  #  CYRILLIC CAPITAL LETTER NJE
    $ent{'TSHcy'}       = chr(0x040B);  #  CYRILLIC CAPITAL LETTER TSHE
    $ent{'KJcy'}        = chr(0x040C);  #  CYRILLIC CAPITAL LETTER KJE
    $ent{'Ubrcy'}       = chr(0x040E);  #  CYRILLIC CAPITAL LETTER SHORT U
    $ent{'DZcy'}        = chr(0x040F);  #  CYRILLIC CAPITAL LETTER DZHE
    $ent{'Acy'}         = chr(0x0410);  #  CYRILLIC CAPITAL LETTER A
    $ent{'Bcy'}         = chr(0x0411);  #  CYRILLIC CAPITAL LETTER BE
    $ent{'Vcy'}         = chr(0x0412);  #  CYRILLIC CAPITAL LETTER VE
    $ent{'Gcy'}         = chr(0x0413);  #  CYRILLIC CAPITAL LETTER GHE
    $ent{'Dcy'}         = chr(0x0414);  #  CYRILLIC CAPITAL LETTER DE
    $ent{'IEcy'}        = chr(0x0415);  #  CYRILLIC CAPITAL LETTER IE
    $ent{'ZHcy'}        = chr(0x0416);  #  CYRILLIC CAPITAL LETTER ZHE
    $ent{'Zcy'}         = chr(0x0417);  #  CYRILLIC CAPITAL LETTER ZE
    $ent{'Icy'}         = chr(0x0418);  #  CYRILLIC CAPITAL LETTER I
    $ent{'Jcy'}         = chr(0x0419);  #  CYRILLIC CAPITAL LETTER SHORT I
    $ent{'Kcy'}         = chr(0x041A);  #  CYRILLIC CAPITAL LETTER KA
    $ent{'Lcy'}         = chr(0x041B);  #  CYRILLIC CAPITAL LETTER EL
    $ent{'Mcy'}         = chr(0x041C);  #  CYRILLIC CAPITAL LETTER EM
    $ent{'Ncy'}         = chr(0x041D);  #  CYRILLIC CAPITAL LETTER EN
    $ent{'Ocy'}         = chr(0x041E);  #  CYRILLIC CAPITAL LETTER O
    $ent{'Pcy'}         = chr(0x041F);  #  CYRILLIC CAPITAL LETTER PE
    $ent{'Rcy'}         = chr(0x0420);  #  CYRILLIC CAPITAL LETTER ER
    $ent{'Scy'}         = chr(0x0421);  #  CYRILLIC CAPITAL LETTER ES
    $ent{'Tcy'}         = chr(0x0422);  #  CYRILLIC CAPITAL LETTER TE
    $ent{'Ucy'}         = chr(0x0423);  #  CYRILLIC CAPITAL LETTER U
    $ent{'Fcy'}         = chr(0x0424);  #  CYRILLIC CAPITAL LETTER EF
    $ent{'KHcy'}        = chr(0x0425);  #  CYRILLIC CAPITAL LETTER HA
    $ent{'TScy'}        = chr(0x0426);  #  CYRILLIC CAPITAL LETTER TSE
    $ent{'CHcy'}        = chr(0x0427);  #  CYRILLIC CAPITAL LETTER CHE
    $ent{'SHcy'}        = chr(0x0428);  #  CYRILLIC CAPITAL LETTER SHA
    $ent{'SHCHcy'}      = chr(0x0429);  #  CYRILLIC CAPITAL LETTER SHCHA
    $ent{'HARDcy'}      = chr(0x042A);  #  CYRILLIC CAPITAL LETTER HARD SIGN
    $ent{'Ycy'}         = chr(0x042B);  #  CYRILLIC CAPITAL LETTER YERU
    $ent{'SOFTcy'}      = chr(0x042C);  #  CYRILLIC CAPITAL LETTER SOFT SIGN
    $ent{'Ecy'}         = chr(0x042D);  #  CYRILLIC CAPITAL LETTER E
    $ent{'YUcy'}        = chr(0x042E);  #  CYRILLIC CAPITAL LETTER YU
    $ent{'YAcy'}        = chr(0x042F);  #  CYRILLIC CAPITAL LETTER YA
    $ent{'acy'}         = chr(0x0430);  #  CYRILLIC SMALL LETTER A
    $ent{'bcy'}         = chr(0x0431);  #  CYRILLIC SMALL LETTER BE
    $ent{'vcy'}         = chr(0x0432);  #  CYRILLIC SMALL LETTER VE
    $ent{'gcy'}         = chr(0x0433);  #  CYRILLIC SMALL LETTER GHE
    $ent{'dcy'}         = chr(0x0434);  #  CYRILLIC SMALL LETTER DE
    $ent{'iecy'}        = chr(0x0435);  #  CYRILLIC SMALL LETTER IE
    $ent{'zhcy'}        = chr(0x0436);  #  CYRILLIC SMALL LETTER ZHE
    $ent{'zcy'}         = chr(0x0437);  #  CYRILLIC SMALL LETTER ZE
    $ent{'icy'}         = chr(0x0438);  #  CYRILLIC SMALL LETTER I
    $ent{'jcy'}         = chr(0x0439);  #  CYRILLIC SMALL LETTER SHORT I
    $ent{'kcy'}         = chr(0x043A);  #  CYRILLIC SMALL LETTER KA
    $ent{'lcy'}         = chr(0x043B);  #  CYRILLIC SMALL LETTER EL
    $ent{'mcy'}         = chr(0x043C);  #  CYRILLIC SMALL LETTER EM
    $ent{'ncy'}         = chr(0x043D);  #  CYRILLIC SMALL LETTER EN
    $ent{'ocy'}         = chr(0x043E);  #  CYRILLIC SMALL LETTER O
    $ent{'pcy'}         = chr(0x043F);  #  CYRILLIC SMALL LETTER PE
    $ent{'rcy'}         = chr(0x0440);  #  CYRILLIC SMALL LETTER ER
    $ent{'scy'}         = chr(0x0441);  #  CYRILLIC SMALL LETTER ES
    $ent{'tcy'}         = chr(0x0442);  #  CYRILLIC SMALL LETTER TE
    $ent{'ucy'}         = chr(0x0443);  #  CYRILLIC SMALL LETTER U
    $ent{'fcy'}         = chr(0x0444);  #  CYRILLIC SMALL LETTER EF
    $ent{'khcy'}        = chr(0x0445);  #  CYRILLIC SMALL LETTER HA
    $ent{'tscy'}        = chr(0x0446);  #  CYRILLIC SMALL LETTER TSE
    $ent{'chcy'}        = chr(0x0447);  #  CYRILLIC SMALL LETTER CHE
    $ent{'shcy'}        = chr(0x0448);  #  CYRILLIC SMALL LETTER SHA
    $ent{'shchcy'}      = chr(0x0449);  #  CYRILLIC SMALL LETTER SHCHA
    $ent{'hardcy'}      = chr(0x044A);  #  CYRILLIC SMALL LETTER HARD SIGN
    $ent{'ycy'}         = chr(0x044B);  #  CYRILLIC SMALL LETTER YERU
    $ent{'softcy'}      = chr(0x044C);  #  CYRILLIC SMALL LETTER SOFT SIGN
    $ent{'ecy'}         = chr(0x044D);  #  CYRILLIC SMALL LETTER E
    $ent{'yucy'}        = chr(0x044E);  #  CYRILLIC SMALL LETTER YU
    $ent{'yacy'}        = chr(0x044F);  #  CYRILLIC SMALL LETTER YA
    $ent{'iocy'}        = chr(0x0451);  #  CYRILLIC SMALL LETTER IO
    $ent{'djcy'}        = chr(0x0452);  #  CYRILLIC SMALL LETTER DJE
    $ent{'gjcy'}        = chr(0x0453);  #  CYRILLIC SMALL LETTER GJE
    $ent{'jukcy'}       = chr(0x0454);  #  CYRILLIC SMALL LETTER UKRAINIAN IE
    $ent{'dscy'}        = chr(0x0455);  #  CYRILLIC SMALL LETTER DZE
    $ent{'iukcy'}       = chr(0x0456);  #  CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
    $ent{'yicy'}        = chr(0x0457);  #  CYRILLIC SMALL LETTER YI
    $ent{'jsercy'}      = chr(0x0458);  #  CYRILLIC SMALL LETTER JE
    $ent{'ljcy'}        = chr(0x0459);  #  CYRILLIC SMALL LETTER LJE
    $ent{'njcy'}        = chr(0x045A);  #  CYRILLIC SMALL LETTER NJE
    $ent{'tshcy'}       = chr(0x045B);  #  CYRILLIC SMALL LETTER TSHE
    $ent{'kjcy'}        = chr(0x045C);  #  CYRILLIC SMALL LETTER KJE
    $ent{'ubrcy'}       = chr(0x045E);  #  CYRILLIC SMALL LETTER SHORT U
    $ent{'dzcy'}        = chr(0x045F);  #  CYRILLIC SMALL LETTER DZHE


    $ent{'Acihk'}       = chr(0x1EA8);  #  LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
    $ent{'acihk'}       = chr(0x1EA9);  #  LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
    $ent{'Abrgr'}       = chr(0x1EB0);  #  LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
    $ent{'abrgr'}       = chr(0x1EB1);  #  LATIN SMALL LETTER A WITH BREVE AND GRAVE
    $ent{'Ociac'}       = chr(0x1ED0);  #  LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
    $ent{'ociac'}       = chr(0x1ED1);  #  LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
    $ent{'Ocihk'}       = chr(0x1ED4);  #  LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
    $ent{'ocihk'}       = chr(0x1ED5);  #  LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
    $ent{'Ohoac'}       = chr(0x1EDA);  #  LATIN CAPITAL LETTER O WITH HORN AND ACUTE
    $ent{'ohoac'}       = chr(0x1EDB);  #  LATIN SMALL LETTER O WITH HORN AND ACUTE
    $ent{'Ohogr'}       = chr(0x1EDC);  #  LATIN CAPITAL LETTER O WITH HORN AND GRAVE
    $ent{'ohogr'}       = chr(0x1EDD);  #  LATIN SMALL LETTER O WITH HORN AND GRAVE
    $ent{'Ohohk'}       = chr(0x1EDE);  #  LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
    $ent{'ohohk'}       = chr(0x1EDF);  #  LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
    $ent{'Ohotl'}       = chr(0x1EE0);  #  LATIN CAPITAL LETTER O WITH HORN AND TILDE
    $ent{'ohotl'}       = chr(0x1EE1);  #  LATIN SMALL LETTER O WITH HORN AND TILDE
    $ent{'Ohodb'}       = chr(0x1EE2);  #  LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
    $ent{'ohodb'}       = chr(0x1EE3);  #  LATIN SMALL LETTER O WITH HORN AND DOT BELOW
    $ent{'Uhoac'}       = chr(0x1EE8);  #  LATIN CAPITAL LETTER U WITH HORN AND ACUTE
    $ent{'uhoac'}       = chr(0x1EE9);  #  LATIN SMALL LETTER U WITH HORN AND ACUTE
    $ent{'Uhogr'}       = chr(0x1EEA);  #  LATIN CAPITAL LETTER U WITH HORN AND GRAVE
    $ent{'uhogr'}       = chr(0x1EEB);  #  LATIN SMALL LETTER U WITH HORN AND GRAVE
    $ent{'Uhohk'}       = chr(0x1EEC);  #  LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
    $ent{'uhohk'}       = chr(0x1EED);  #  LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
    $ent{'Uhotl'}       = chr(0x1EEE);  #  LATIN CAPITAL LETTER U WITH HORN AND TILDE
    $ent{'uhotl'}       = chr(0x1EEF);  #  LATIN SMALL LETTER U WITH HORN AND TILDE
    $ent{'Uhodb'}       = chr(0x1EF0);  #  LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
    $ent{'uhodb'}       = chr(0x1EF1);  #  LATIN SMALL LETTER U WITH HORN AND DOT BELOW


    $ent{'ensp'}        = chr(0x2002);  #  EN SPACE
    $ent{'emsp'}        = chr(0x2003);  #  EM SPACE
    $ent{'emsp13'}      = chr(0x2004);  #  THREE-PER-EM SPACE
    $ent{'emsp14'}      = chr(0x2005);  #  FOUR-PER-EM SPACE
    $ent{'numsp'}       = chr(0x2007);  #  FIGURE SPACE
    $ent{'puncsp'}      = chr(0x2008);  #  PUNCTUATION SPACE
    $ent{'thinsp'}      = chr(0x2009);  #  THIN SPACE
    $ent{'hairsp'}      = chr(0x200A);  #  HAIR SPACE
    $ent{'zwsp'}        = chr(0x200B);  #  ZERO WIDTH SPACE
    $ent{'zwnj'}        = chr(0x200C);  #  ZERO WIDTH NON-JOINER
    $ent{'zwj'}         = chr(0x200D);  #  ZERO WIDTH JOINER
    $ent{'dash'}        = chr(0x2010);  #  HYPHEN
    $ent{'ndash'}       = chr(0x2013);  #  EN DASH
    $ent{'mdash'}       = chr(0x2014);  #  EM DASH
    $ent{'horbar'}      = chr(0x2015);  #  HORIZONTAL BAR
    $ent{'Verbar'}      = chr(0x2016);  #  DOUBLE VERTICAL LINE
    $ent{'lsquo'}       = chr(0x2018);  #  LEFT SINGLE QUOTATION MARK
    $ent{'rsquo'}       = chr(0x2019);  #  RIGHT SINGLE QUOTATION MARK
    $ent{'sbquo'}       = chr(0x201A);  #  SINGLE LOW-9 QUOTATION MARK
    $ent{'ldquo'}       = chr(0x201C);  #  LEFT DOUBLE QUOTATION MARK
    $ent{'rdquo'}       = chr(0x201D);  #  RIGHT DOUBLE QUOTATION MARK
    $ent{'bdquo'}       = chr(0x201E);  #  DOUBLE LOW-9 QUOTATION MARK
    $ent{'dagger'}      = chr(0x2020);  #  DAGGER
    $ent{'Dagger'}      = chr(0x2021);  #  DOUBLE DAGGER
    $ent{'bull'}        = chr(0x2022);  #  BULLET
    $ent{'nldr'}        = chr(0x2025);  #  TWO DOT LEADER
    $ent{'hellip'}      = chr(0x2026);  #  HORIZONTAL ELLIPSIS
    $ent{'permil'}      = chr(0x2030);  #  PER MILLE SIGN
    $ent{'prime'}       = chr(0x2032);  #  PRIME
    $ent{'Prime'}       = chr(0x2033);  #  DOUBLE PRIME
    $ent{'tprime'}      = chr(0x2034);  #  TRIPLE PRIME
    $ent{'bprime'}      = chr(0x2035);  #  REVERSED PRIME
    $ent{'lsaquo'}      = chr(0x2039);  #  SINGLE LEFT-POINTING ANGLE QUOTATION MARK
    $ent{'rsaquo'}      = chr(0x203A);  #  SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
    $ent{'oline'}       = chr(0x203E);  #  OVERLINE
    $ent{'caret'}       = chr(0x2041);  #  CARET INSERTION POINT
    $ent{'hybull'}      = chr(0x2043);  #  HYPHEN BULLET
    $ent{'frasl'}       = chr(0x2044);  #  FRACTION SLASH
    $ent{'sup0'}        = chr(0x2070);  #  SUPERSCRIPT ZERO
    $ent{'sup4'}        = chr(0x2074);  #  SUPERSCRIPT FOUR
    $ent{'sup5'}        = chr(0x2075);  #  SUPERSCRIPT FIVE
    $ent{'sup6'}        = chr(0x2076);  #  SUPERSCRIPT SIX
    $ent{'sup7'}        = chr(0x2077);  #  SUPERSCRIPT SEVEN
    $ent{'sup8'}        = chr(0x2078);  #  SUPERSCRIPT EIGHT
    $ent{'sup9'}        = chr(0x2079);  #  SUPERSCRIPT NINE
    $ent{'supmin'}      = chr(0x207B);  #  SUPERSCRIPT MINUS
    $ent{'tdot'}        = chr(0x20DB);  #  COMBINING THREE DOTS ABOVE
    $ent{'DotDot'}      = chr(0x20DC);  #  COMBINING FOUR DOTS ABOVE


    $ent{'incare'}      = chr(0x2105);  #  CARE OF
    $ent{'hamilt'}      = chr(0x210B);  #  SCRIPT CAPITAL H
    $ent{'planck'}      = chr(0x210F);  #  PLANCK CONSTANT OVER TWO PI
    $ent{'image'}       = chr(0x2111);  #  BLACK-LETTER CAPITAL I
    $ent{'lagran'}      = chr(0x2112);  #  SCRIPT CAPITAL L
    $ent{'ell'}         = chr(0x2113);  #  SCRIPT SMALL L
    $ent{'numero'}      = chr(0x2116);  #  NUMERO SIGN
    $ent{'copysr'}      = chr(0x2117);  #  SOUND RECORDING COPYRIGHT
    $ent{'weierp'}      = chr(0x2118);  #  SCRIPT CAPITAL P
    $ent{'real'}        = chr(0x211C);  #  BLACK-LETTER CAPITAL R
    $ent{'rx'}          = chr(0x211E);  #  PRESCRIPTION TAKE
    $ent{'trade'}       = chr(0x2122);  #  TRADE MARK SIGN
    $ent{'ohm'}         = chr(0x2126);  #  OHM SIGN
    $ent{'angst'}       = chr(0x212B);  #  ANGSTROM SIGN
    $ent{'bernou'}      = chr(0x212C);  #  SCRIPT CAPITAL B
    $ent{'phmmat'}      = chr(0x2133);  #  SCRIPT CAPITAL M
    $ent{'order'}       = chr(0x2134);  #  SCRIPT SMALL O
    $ent{'aleph'}       = chr(0x2135);  #  ALEF SYMBOL
    $ent{'beth'}        = chr(0x2136);  #  BET SYMBOL
    $ent{'gimel'}       = chr(0x2137);  #  GIMEL SYMBOL
    $ent{'daleth'}      = chr(0x2138);  #  DALET SYMBOL
    $ent{'frac13'}      = chr(0x2153);  #  VULGAR FRACTION ONE THIRD
    $ent{'frac23'}      = chr(0x2154);  #  VULGAR FRACTION TWO THIRDS
    $ent{'frac15'}      = chr(0x2155);  #  VULGAR FRACTION ONE FIFTH
    $ent{'frac25'}      = chr(0x2156);  #  VULGAR FRACTION TWO FIFTHS
    $ent{'frac35'}      = chr(0x2157);  #  VULGAR FRACTION THREE FIFTHS
    $ent{'frac45'}      = chr(0x2158);  #  VULGAR FRACTION FOUR FIFTHS
    $ent{'frac16'}      = chr(0x2159);  #  VULGAR FRACTION ONE SIXTH
    $ent{'frac56'}      = chr(0x215A);  #  VULGAR FRACTION FIVE SIXTHS
    $ent{'frac18'}      = chr(0x215B);  #  VULGAR FRACTION ONE EIGHTH
    $ent{'frac38'}      = chr(0x215C);  #  VULGAR FRACTION THREE EIGHTHS
    $ent{'frac58'}      = chr(0x215D);  #  VULGAR FRACTION FIVE EIGHTHS
    $ent{'frac78'}      = chr(0x215E);  #  VULGAR FRACTION SEVEN EIGHTHS
    $ent{'larr'}        = chr(0x2190);  #  LEFTWARDS ARROW
    $ent{'uarr'}        = chr(0x2191);  #  UPWARDS ARROW
    $ent{'rarr'}        = chr(0x2192);  #  RIGHTWARDS ARROW
    $ent{'darr'}        = chr(0x2193);  #  DOWNWARDS ARROW
    $ent{'harr'}        = chr(0x2194);  #  LEFT RIGHT ARROW
    $ent{'varr'}        = chr(0x2195);  #  UP DOWN ARROW
    $ent{'nwarr'}       = chr(0x2196);  #  NORTH WEST ARROW
    $ent{'nearr'}       = chr(0x2197);  #  NORTH EAST ARROW
    $ent{'drarr'}       = chr(0x2198);  #  SOUTH EAST ARROW
    $ent{'dlarr'}       = chr(0x2199);  #  SOUTH WEST ARROW
    $ent{'nlarr'}       = chr(0x219A);  #  LEFTWARDS ARROW WITH STROKE
    $ent{'nrarr'}       = chr(0x219B);  #  RIGHTWARDS ARROW WITH STROKE
    $ent{'rarrw'}       = chr(0x219D);  #  RIGHTWARDS WAVE ARROW
    $ent{'Larr'}        = chr(0x219E);  #  LEFTWARDS TWO HEADED ARROW
    $ent{'Rarr'}        = chr(0x21A0);  #  RIGHTWARDS TWO HEADED ARROW
    $ent{'larrtl'}      = chr(0x21A2);  #  LEFTWARDS ARROW WITH TAIL
    $ent{'rarrtl'}      = chr(0x21A3);  #  RIGHTWARDS ARROW WITH TAIL
    $ent{'map'}         = chr(0x21A6);  #  RIGHTWARDS ARROW FROM BAR
    $ent{'larrhk'}      = chr(0x21A9);  #  LEFTWARDS ARROW WITH HOOK
    $ent{'rarrhk'}      = chr(0x21AA);  #  RIGHTWARDS ARROW WITH HOOK
    $ent{'larrlp'}      = chr(0x21AB);  #  LEFTWARDS ARROW WITH LOOP
    $ent{'rarrlp'}      = chr(0x21AC);  #  RIGHTWARDS ARROW WITH LOOP
    $ent{'harrw'}       = chr(0x21AD);  #  LEFT RIGHT WAVE ARROW
    $ent{'nharr'}       = chr(0x21AE);  #  LEFT RIGHT ARROW WITH STROKE
    $ent{'lsh'}         = chr(0x21B0);  #  UPWARDS ARROW WITH TIP LEFTWARDS
    $ent{'rsh'}         = chr(0x21B1);  #  UPWARDS ARROW WITH TIP RIGHTWARDS
    $ent{'crarr'}       = chr(0x21B5);  #  DOWNWARDS ARROW WITH CORNER LEFTWARDS
    $ent{'cularr'}      = chr(0x21B6);  #  ANTICLOCKWISE TOP SEMICIRCLE ARROW
    $ent{'curarr'}      = chr(0x21B7);  #  CLOCKWISE TOP SEMICIRCLE ARROW
    $ent{'olarr'}       = chr(0x21BA);  #  ANTICLOCKWISE OPEN CIRCLE ARROW
    $ent{'orarr'}       = chr(0x21BB);  #  CLOCKWISE OPEN CIRCLE ARROW
    $ent{'lharu'}       = chr(0x21BC);  #  LEFTWARDS HARPOON WITH BARB UPWARDS
    $ent{'lhard'}       = chr(0x21BD);  #  LEFTWARDS HARPOON WITH BARB DOWNWARDS
    $ent{'uharr'}       = chr(0x21BE);  #  UPWARDS HARPOON WITH BARB RIGHTWARDS
    $ent{'uharl'}       = chr(0x21BF);  #  UPWARDS HARPOON WITH BARB LEFTWARDS
    $ent{'rharu'}       = chr(0x21C0);  #  RIGHTWARDS HARPOON WITH BARB UPWARDS
    $ent{'rhard'}       = chr(0x21C1);  #  RIGHTWARDS HARPOON WITH BARB DOWNWARDS
    $ent{'dharr'}       = chr(0x21C2);  #  DOWNWARDS HARPOON WITH BARB RIGHTWARDS
    $ent{'dharl'}       = chr(0x21C3);  #  DOWNWARDS HARPOON WITH BARB LEFTWARDS
    $ent{'rlarr2'}      = chr(0x21C4);  #  RIGHTWARDS ARROW OVER LEFTWARDS ARROW
    $ent{'lrarr2'}      = chr(0x21C6);  #  LEFTWARDS ARROW OVER RIGHTWARDS ARROW
    $ent{'larr2'}       = chr(0x21C7);  #  LEFTWARDS PAIRED ARROWS
    $ent{'uarr2'}       = chr(0x21C8);  #  UPWARDS PAIRED ARROWS
    $ent{'rarr2'}       = chr(0x21C9);  #  RIGHTWARDS PAIRED ARROWS
    $ent{'darr2'}       = chr(0x21CA);  #  DOWNWARDS PAIRED ARROWS
    $ent{'lrhar2'}      = chr(0x21CB);  #  LEFTWARDS HARPOON OVER RIGHTWARDS HARPOON
    $ent{'rlhar2'}      = chr(0x21CC);  #  RIGHTWARDS HARPOON OVER LEFTWARDS HARPOON
    $ent{'nlArr'}       = chr(0x21CD);  #  LEFTWARDS DOUBLE ARROW WITH STROKE
    $ent{'nhArr'}       = chr(0x21CE);  #  LEFT RIGHT DOUBLE ARROW WITH STROKE
    $ent{'nrArr'}       = chr(0x21CF);  #  RIGHTWARDS DOUBLE ARROW WITH STROKE
    $ent{'lArr'}        = chr(0x21D0);  #  LEFTWARDS DOUBLE ARROW
    $ent{'uArr'}        = chr(0x21D1);  #  UPWARDS DOUBLE ARROW
    $ent{'rArr'}        = chr(0x21D2);  #  RIGHTWARDS DOUBLE ARROW
    $ent{'dArr'}        = chr(0x21D3);  #  DOWNWARDS DOUBLE ARROW
    $ent{'hArr'}        = chr(0x21D4);  #  LEFT RIGHT DOUBLE ARROW
    $ent{'vArr'}        = chr(0x21D5);  #  UP DOWN DOUBLE ARROW
    $ent{'lAarr'}       = chr(0x21DA);  #  LEFTWARDS TRIPLE ARROW
    $ent{'rAarr'}       = chr(0x21DB);  #  RIGHTWARDS TRIPLE ARROW


    $ent{'forall'}      = chr(0x2200);  #  FOR ALL
    $ent{'comp'}        = chr(0x2201);  #  COMPLEMENT
    $ent{'part'}        = chr(0x2202);  #  PARTIAL DIFFERENTIAL
    $ent{'exist'}       = chr(0x2203);  #  THERE EXISTS
    $ent{'nexist'}      = chr(0x2204);  #  THERE DOES NOT EXIST
    $ent{'empty'}       = chr(0x2205);  #  EMPTY SET
    $ent{'nabla'}       = chr(0x2207);  #  NABLA
    $ent{'isin'}        = chr(0x2208);  #  ELEMENT OF
    $ent{'notin'}       = chr(0x2209);  #  NOT AN ELEMENT OF
    $ent{'epsis'}       = chr(0x220A);  #  SMALL ELEMENT OF
    $ent{'ni'}          = chr(0x220B);  #  CONTAINS AS MEMBER
    $ent{'bepsi'}       = chr(0x220D);  #  SMALL CONTAINS AS MEMBER
    $ent{'prod'}        = chr(0x220F);  #  N-ARY PRODUCT
    $ent{'coprod'}      = chr(0x2210);  #  N-ARY COPRODUCT
    $ent{'sum'}         = chr(0x2211);  #  N-ARY SUMMATION
    $ent{'minus'}       = chr(0x2212);  #  MINUS SIGN
    $ent{'mnplus'}      = chr(0x2213);  #  MINUS-OR-PLUS SIGN
    $ent{'plusdo'}      = chr(0x2214);  #  DOT PLUS
    $ent{'setmn'}       = chr(0x2216);  #  SET MINUS
    $ent{'lowast'}      = chr(0x2217);  #  ASTERISK OPERATOR
    $ent{'compfn'}      = chr(0x2218);  #  RING OPERATOR
    $ent{'radic'}       = chr(0x221A);  #  SQUARE ROOT
    $ent{'vprop'}       = chr(0x221D);  #  PROPORTIONAL TO
    $ent{'infin'}       = chr(0x221E);  #  INFINITY
    $ent{'ang90'}       = chr(0x221F);  #  RIGHT ANGLE
    $ent{'ang'}         = chr(0x2220);  #  ANGLE
    $ent{'angmsd'}      = chr(0x2221);  #  MEASURED ANGLE
    $ent{'angsph'}      = chr(0x2222);  #  SPHERICAL ANGLE
    $ent{'mid'}         = chr(0x2223);  #  DIVIDES
    $ent{'nmid'}        = chr(0x2224);  #  DOES NOT DIVIDE
    $ent{'par'}         = chr(0x2225);  #  PARALLEL TO
    $ent{'npar'}        = chr(0x2226);  #  NOT PARALLEL TO
    $ent{'and'}         = chr(0x2227);  #  LOGICAL AND
    $ent{'or'}          = chr(0x2228);  #  LOGICAL OR
    $ent{'cap'}         = chr(0x2229);  #  INTERSECTION
    $ent{'cup'}         = chr(0x222A);  #  UNION
    $ent{'int'}         = chr(0x222B);  #  INTEGRAL
    $ent{'conint'}      = chr(0x222E);  #  CONTOUR INTEGRAL
    $ent{'there4'}      = chr(0x2234);  #  THEREFORE
    $ent{'becaus'}      = chr(0x2235);  #  BECAUSE
    $ent{'sim'}         = chr(0x223C);  #  TILDE OPERATOR
    $ent{'bsim'}        = chr(0x223D);  #  REVERSED TILDE
    $ent{'wreath'}      = chr(0x2240);  #  WREATH PRODUCT
    $ent{'nsim'}        = chr(0x2241);  #  NOT TILDE
    $ent{'sime'}        = chr(0x2243);  #  ASYMPTOTICALLY EQUAL TO
    $ent{'nsime'}       = chr(0x2244);  #  NOT ASYMPTOTICALLY EQUAL TO
    $ent{'cong'}        = chr(0x2245);  #  APPROXIMATELY EQUAL TO
    $ent{'ncong'}       = chr(0x2247);  #  NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO
    $ent{'ap'}          = chr(0x2248);  #  ALMOST EQUAL TO
    $ent{'nap'}         = chr(0x2249);  #  NOT ALMOST EQUAL TO
    $ent{'ape'}         = chr(0x224A);  #  ALMOST EQUAL OR EQUAL TO
    $ent{'bcong'}       = chr(0x224C);  #  ALL EQUAL TO
    $ent{'bump'}        = chr(0x224E);  #  GEOMETRICALLY EQUIVALENT TO
    $ent{'bumpe'}       = chr(0x224F);  #  DIFFERENCE BETWEEN
    $ent{'esdot'}       = chr(0x2250);  #  APPROACHES THE LIMIT
    $ent{'eDot'}        = chr(0x2251);  #  GEOMETRICALLY EQUAL TO
    $ent{'efDot'}       = chr(0x2252);  #  APPROXIMATELY EQUAL TO OR THE IMAGE OF
    $ent{'erDot'}       = chr(0x2253);  #  IMAGE OF OR APPROXIMATELY EQUAL TO
    $ent{'colone'}      = chr(0x2254);  #  COLON EQUALS
    $ent{'ecolon'}      = chr(0x2255);  #  EQUALS COLON
    $ent{'ecir'}        = chr(0x2256);  #  RING IN EQUAL TO
    $ent{'cire'}        = chr(0x2257);  #  RING EQUAL TO
    $ent{'wedgeq'}      = chr(0x2259);  #  ESTIMATES
    $ent{'trie'}        = chr(0x225C);  #  DELTA EQUAL TO
    $ent{'ne'}          = chr(0x2260);  #  NOT EQUAL TO
    $ent{'equiv'}       = chr(0x2261);  #  IDENTICAL TO
    $ent{'nequiv'}      = chr(0x2262);  #  NOT IDENTICAL TO
    $ent{'le'}          = chr(0x2264);  #  LESS-THAN OR EQUAL TO
    $ent{'ge'}          = chr(0x2265);  #  GREATER-THAN OR EQUAL TO
    $ent{'lE'}          = chr(0x2266);  #  LESS-THAN OVER EQUAL TO
    $ent{'gE'}          = chr(0x2267);  #  GREATER-THAN OVER EQUAL TO
    $ent{'lne'}         = chr(0x2268);  #  LESS-THAN BUT NOT EQUAL TO
    $ent{'gne'}         = chr(0x2269);  #  GREATER-THAN BUT NOT EQUAL TO
    $ent{'Lt'}          = chr(0x226A);  #  MUCH LESS-THAN
    $ent{'Gt'}          = chr(0x226B);  #  MUCH GREATER-THAN
    $ent{'twixt'}       = chr(0x226C);  #  BETWEEN
    $ent{'nlt'}         = chr(0x226E);  #  NOT LESS-THAN
    $ent{'ngt'}         = chr(0x226F);  #  NOT GREATER-THAN
    $ent{'nle'}         = chr(0x2270);  #  NEITHER LESS-THAN NOR EQUAL TO
    $ent{'nge'}         = chr(0x2271);  #  NEITHER GREATER-THAN NOR EQUAL TO
    $ent{'lsim'}        = chr(0x2272);  #  LESS-THAN OR EQUIVALENT TO
    $ent{'gsim'}        = chr(0x2273);  #  GREATER-THAN OR EQUIVALENT TO
    $ent{'lg'}          = chr(0x2276);  #  LESS-THAN OR GREATER-THAN
    $ent{'gl'}          = chr(0x2277);  #  GREATER-THAN OR LESS-THAN
    $ent{'pr'}          = chr(0x227A);  #  PRECEDES
    $ent{'sc'}          = chr(0x227B);  #  SUCCEEDS
    $ent{'pre'}         = chr(0x227C);  #  PRECEDES OR EQUAL TO
    $ent{'sce'}         = chr(0x227D);  #  SUCCEEDS OR EQUAL TO
    $ent{'prsim'}       = chr(0x227E);  #  PRECEDES OR EQUIVALENT TO
    $ent{'scsim'}       = chr(0x227F);  #  SUCCEEDS OR EQUIVALENT TO
    $ent{'npr'}         = chr(0x2280);  #  DOES NOT PRECEDE
    $ent{'nsc'}         = chr(0x2281);  #  DOES NOT SUCCEED
    $ent{'sub'}         = chr(0x2282);  #  SUBSET OF
    $ent{'sup'}         = chr(0x2283);  #  SUPERSET OF
    $ent{'nsub'}        = chr(0x2284);  #  NOT A SUBSET OF
    $ent{'nsup'}        = chr(0x2285);  #  NOT A SUPERSET OF
    $ent{'sube'}        = chr(0x2286);  #  SUBSET OF OR EQUAL TO
    $ent{'supe'}        = chr(0x2287);  #  SUPERSET OF OR EQUAL TO
    $ent{'nsube'}       = chr(0x2288);  #  NEITHER A SUBSET OF NOR EQUAL TO
    $ent{'nsupe'}       = chr(0x2289);  #  NEITHER A SUPERSET OF NOR EQUAL TO
    $ent{'subne'}       = chr(0x228A);  #  SUBSET OF WITH NOT EQUAL TO
    $ent{'supne'}       = chr(0x228B);  #  SUPERSET OF WITH NOT EQUAL TO
    $ent{'uplus'}       = chr(0x228E);  #  MULTISET UNION
    $ent{'sqsub'}       = chr(0x228F);  #  SQUARE IMAGE OF
    $ent{'sqsup'}       = chr(0x2290);  #  SQUARE ORIGINAL OF
    $ent{'sqsube'}      = chr(0x2291);  #  SQUARE IMAGE OF OR EQUAL TO
    $ent{'sqsupe'}      = chr(0x2292);  #  SQUARE ORIGINAL OF OR EQUAL TO
    $ent{'sqcap'}       = chr(0x2293);  #  SQUARE CAP
    $ent{'sqcup'}       = chr(0x2294);  #  SQUARE CUP
    $ent{'oplus'}       = chr(0x2295);  #  CIRCLED PLUS
    $ent{'ominus'}      = chr(0x2296);  #  CIRCLED MINUS
    $ent{'otimes'}      = chr(0x2297);  #  CIRCLED TIMES
    $ent{'osol'}        = chr(0x2298);  #  CIRCLED DIVISION SLASH
    $ent{'odot'}        = chr(0x2299);  #  CIRCLED DOT OPERATOR
    $ent{'ocir'}        = chr(0x229A);  #  CIRCLED RING OPERATOR
    $ent{'oast'}        = chr(0x229B);  #  CIRCLED ASTERISK OPERATOR
    $ent{'odash'}       = chr(0x229D);  #  CIRCLED DASH
    $ent{'plusb'}       = chr(0x229E);  #  SQUARED PLUS
    $ent{'minusb'}      = chr(0x229F);  #  SQUARED MINUS
    $ent{'timesb'}      = chr(0x22A0);  #  SQUARED TIMES
    $ent{'sdotb'}       = chr(0x22A1);  #  SQUARED DOT OPERATOR
    $ent{'vdash'}       = chr(0x22A2);  #  RIGHT TACK
    $ent{'dashv'}       = chr(0x22A3);  #  LEFT TACK
    $ent{'top'}         = chr(0x22A4);  #  DOWN TACK
    $ent{'bottom'}      = chr(0x22A5);  #  UP TACK
    $ent{'models'}      = chr(0x22A7);  #  MODELS
    $ent{'vDash'}       = chr(0x22A8);  #  TRUE
    $ent{'Vdash'}       = chr(0x22A9);  #  FORCES
    $ent{'Vvdash'}      = chr(0x22AA);  #  TRIPLE VERTICAL BAR RIGHT TURNSTILE
    $ent{'nvdash'}      = chr(0x22AC);  #  DOES NOT PROVE
    $ent{'nvDash'}      = chr(0x22AD);  #  NOT TRUE
    $ent{'nVdash'}      = chr(0x22AE);  #  DOES NOT FORCE
    $ent{'nVDash'}      = chr(0x22AF);  #  NEGATED DOUBLE VERTICAL BAR DOUBLE RIGHT
    $ent{'vltri'}       = chr(0x22B2);  #  NORMAL SUBGROUP OF
    $ent{'vrtri'}       = chr(0x22B3);  #  CONTAINS AS NORMAL SUBGROUP
    $ent{'ltrie'}       = chr(0x22B4);  #  NORMAL SUBGROUP OF OR EQUAL TO
    $ent{'rtrie'}       = chr(0x22B5);  #  CONTAINS AS NORMAL SUBGROUP OR EQUAL TO
    $ent{'mumap'}       = chr(0x22B8);  #  MULTIMAP
    $ent{'intcal'}      = chr(0x22BA);  #  INTERCALATE
    $ent{'veebar'}      = chr(0x22BB);  #  XOR
    $ent{'barwed'}      = chr(0x22BC);  #  NAND
    $ent{'diam'}        = chr(0x22C4);  #  DIAMOND OPERATOR
    $ent{'sdot'}        = chr(0x22C5);  #  DOT OPERATOR
    $ent{'sstarf'}      = chr(0x22C6);  #  STAR OPERATOR
    $ent{'divonx'}      = chr(0x22C7);  #  DIVISION TIMES
    $ent{'bowtie'}      = chr(0x22C8);  #  BOWTIE
    $ent{'ltimes'}      = chr(0x22C9);  #  LEFT NORMAL FACTOR SEMIDIRECT PRODUCT
    $ent{'rtimes'}      = chr(0x22CA);  #  RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT
    $ent{'lthree'}      = chr(0x22CB);  #  LEFT SEMIDIRECT PRODUCT
    $ent{'rthree'}      = chr(0x22CC);  #  RIGHT SEMIDIRECT PRODUCT
    $ent{'bsime'}       = chr(0x22CD);  #  REVERSED TILDE EQUALS
    $ent{'cuvee'}       = chr(0x22CE);  #  CURLY LOGICAL OR
    $ent{'cuwed'}       = chr(0x22CF);  #  CURLY LOGICAL AND
    $ent{'Sub'}         = chr(0x22D0);  #  DOUBLE SUBSET
    $ent{'Sup'}         = chr(0x22D1);  #  DOUBLE SUPERSET
    $ent{'Cap'}         = chr(0x22D2);  #  DOUBLE INTERSECTION
    $ent{'Cup'}         = chr(0x22D3);  #  DOUBLE UNION
    $ent{'fork'}        = chr(0x22D4);  #  PITCHFORK
    $ent{'ldot'}        = chr(0x22D6);  #  LESS-THAN WITH DOT
    $ent{'gsdot'}       = chr(0x22D7);  #  GREATER-THAN WITH DOT
    $ent{'Ll'}          = chr(0x22D8);  #  VERY MUCH LESS-THAN
    $ent{'Gg'}          = chr(0x22D9);  #  VERY MUCH GREATER-THAN
    $ent{'leg'}         = chr(0x22DA);  #  LESS-THAN EQUAL TO OR GREATER-THAN
    $ent{'gel'}         = chr(0x22DB);  #  GREATER-THAN EQUAL TO OR LESS-THAN
    $ent{'els'}         = chr(0x22DC);  #  EQUAL TO OR LESS-THAN
    $ent{'egs'}         = chr(0x22DD);  #  EQUAL TO OR GREATER-THAN
    $ent{'cuepr'}       = chr(0x22DE);  #  EQUAL TO OR PRECEDES
    $ent{'cuesc'}       = chr(0x22DF);  #  EQUAL TO OR SUCCEEDS
    $ent{'npre'}        = chr(0x22E0);  #  DOES NOT PRECEDE OR EQUAL
    $ent{'nsce'}        = chr(0x22E1);  #  DOES NOT SUCCEED OR EQUAL
    $ent{'lnsim'}       = chr(0x22E6);  #  LESS-THAN BUT NOT EQUIVALENT TO
    $ent{'gnsim'}       = chr(0x22E7);  #  GREATER-THAN BUT NOT EQUIVALENT TO
    $ent{'prnsim'}      = chr(0x22E8);  #  PRECEDES BUT NOT EQUIVALENT TO
    $ent{'scnsim'}      = chr(0x22E9);  #  SUCCEEDS BUT NOT EQUIVALENT TO
    $ent{'nltri'}       = chr(0x22EA);  #  NOT NORMAL SUBGROUP OF
    $ent{'nrtri'}       = chr(0x22EB);  #  DOES NOT CONTAIN AS NORMAL SUBGROUP
    $ent{'nltrie'}      = chr(0x22EC);  #  NOT NORMAL SUBGROUP OF OR EQUAL TO
    $ent{'nrtrie'}      = chr(0x22ED);  #  DOES NOT CONTAIN AS NORMAL SUBGROUP OR EQUAL
    $ent{'vellip'}      = chr(0x22EE);  #  VERTICAL ELLIPSIS


    $ent{'Barwed'}      = chr(0x2306);  #  PERSPECTIVE
    $ent{'lceil'}       = chr(0x2308);  #  LEFT CEILING
    $ent{'rceil'}       = chr(0x2309);  #  RIGHT CEILING
    $ent{'lfloor'}      = chr(0x230A);  #  LEFT FLOOR
    $ent{'rfloor'}      = chr(0x230B);  #  RIGHT FLOOR
    $ent{'drcrop'}      = chr(0x230C);  #  BOTTOM RIGHT CROP
    $ent{'dlcrop'}      = chr(0x230D);  #  BOTTOM LEFT CROP
    $ent{'urcrop'}      = chr(0x230E);  #  TOP RIGHT CROP
    $ent{'ulcrop'}      = chr(0x230F);  #  TOP LEFT CROP
    $ent{'telrec'}      = chr(0x2315);  #  TELEPHONE RECORDER
    $ent{'target'}      = chr(0x2316);  #  POSITION INDICATOR
    $ent{'ulcorn'}      = chr(0x231C);  #  TOP LEFT CORNER
    $ent{'urcorn'}      = chr(0x231D);  #  TOP RIGHT CORNER
    $ent{'dlcorn'}      = chr(0x231E);  #  BOTTOM LEFT CORNER
    $ent{'drcorn'}      = chr(0x231F);  #  BOTTOM RIGHT CORNER
    $ent{'frown'}       = chr(0x2322);  #  FROWN
    $ent{'smile'}       = chr(0x2323);  #  SMILE
    $ent{'lang'}        = chr(0x2329);  #  LEFT-POINTING ANGLE BRACKET
    $ent{'rang'}        = chr(0x232A);  #  RIGHT-POINTING ANGLE BRACKET
    $ent{'blank'}       = chr(0x2423);  #  OPEN BOX
    $ent{'oS'}          = chr(0x24C8);  #  CIRCLED LATIN CAPITAL LETTER S
    $ent{'boxh'}        = chr(0x2500);  #  BOX DRAWINGS LIGHT HORIZONTAL
    $ent{'boxv'}        = chr(0x2502);  #  BOX DRAWINGS LIGHT VERTICAL
    $ent{'boxdr'}       = chr(0x250C);  #  BOX DRAWINGS LIGHT DOWN AND RIGHT
    $ent{'boxdl'}       = chr(0x2510);  #  BOX DRAWINGS LIGHT DOWN AND LEFT
    $ent{'boxur'}       = chr(0x2514);  #  BOX DRAWINGS LIGHT UP AND RIGHT
    $ent{'boxul'}       = chr(0x2518);  #  BOX DRAWINGS LIGHT UP AND LEFT
    $ent{'boxvr'}       = chr(0x251C);  #  BOX DRAWINGS LIGHT VERTICAL AND RIGHT
    $ent{'boxvl'}       = chr(0x2524);  #  BOX DRAWINGS LIGHT VERTICAL AND LEFT
    $ent{'boxhd'}       = chr(0x252C);  #  BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
    $ent{'boxhu'}       = chr(0x2534);  #  BOX DRAWINGS LIGHT UP AND HORIZONTAL
    $ent{'boxvh'}       = chr(0x253C);  #  BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
    $ent{'boxH'}        = chr(0x2550);  #  BOX DRAWINGS DOUBLE HORIZONTAL
    $ent{'boxV'}        = chr(0x2551);  #  BOX DRAWINGS DOUBLE VERTICAL
    $ent{'boxdR'}       = chr(0x2552);  #  BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
    $ent{'boxDr'}       = chr(0x2553);  #  BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
    $ent{'boxDR'}       = chr(0x2554);  #  BOX DRAWINGS DOUBLE DOWN AND RIGHT
    $ent{'boxdL'}       = chr(0x2555);  #  BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
    $ent{'boxDl'}       = chr(0x2556);  #  BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
    $ent{'boxDL'}       = chr(0x2557);  #  BOX DRAWINGS DOUBLE DOWN AND LEFT
    $ent{'boxuR'}       = chr(0x2558);  #  BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
    $ent{'boxUr'}       = chr(0x2559);  #  BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
    $ent{'boxUR'}       = chr(0x255A);  #  BOX DRAWINGS DOUBLE UP AND RIGHT
    $ent{'boxuL'}       = chr(0x255B);  #  BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
    $ent{'boxUl'}       = chr(0x255C);  #  BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
    $ent{'boxUL'}       = chr(0x255D);  #  BOX DRAWINGS DOUBLE UP AND LEFT
    $ent{'boxvR'}       = chr(0x255E);  #  BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
    $ent{'boxVr'}       = chr(0x255F);  #  BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
    $ent{'boxVR'}       = chr(0x2560);  #  BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
    $ent{'boxvL'}       = chr(0x2561);  #  BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
    $ent{'boxVl'}       = chr(0x2562);  #  BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
    $ent{'boxVL'}       = chr(0x2563);  #  BOX DRAWINGS DOUBLE VERTICAL AND LEFT
    $ent{'boxHd'}       = chr(0x2564);  #  BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
    $ent{'boxhD'}       = chr(0x2565);  #  BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
    $ent{'boxHD'}       = chr(0x2566);  #  BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
    $ent{'boxHu'}       = chr(0x2567);  #  BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
    $ent{'boxhU'}       = chr(0x2568);  #  BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
    $ent{'boxHU'}       = chr(0x2569);  #  BOX DRAWINGS DOUBLE UP AND HORIZONTAL
    $ent{'boxvH'}       = chr(0x256A);  #  BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
    $ent{'boxVh'}       = chr(0x256B);  #  BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
    $ent{'boxVH'}       = chr(0x256C);  #  BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
    $ent{'uhblk'}       = chr(0x2580);  #  UPPER HALF BLOCK
    $ent{'lhblk'}       = chr(0x2584);  #  LOWER HALF BLOCK
    $ent{'block'}       = chr(0x2588);  #  FULL BLOCK
    $ent{'blk14'}       = chr(0x2591);  #  LIGHT SHADE
    $ent{'blk12'}       = chr(0x2592);  #  MEDIUM SHADE
    $ent{'blk34'}       = chr(0x2593);  #  DARK SHADE
    $ent{'square'}      = chr(0x25A1);  #  WHITE SQUARE
    $ent{'squf'}        = chr(0x25AA);  #  BLACK SMALL SQUARE
    $ent{'rect'}        = chr(0x25AD);  #  WHITE RECTANGLE
    $ent{'marker'}      = chr(0x25AE);  #  BLACK VERTICAL RECTANGLE
    $ent{'utrif'}       = chr(0x25B4);  #  BLACK UP-POINTING SMALL TRIANGLE
    $ent{'utri'}        = chr(0x25B5);  #  WHITE UP-POINTING SMALL TRIANGLE
    $ent{'rtrif'}       = chr(0x25B8);  #  BLACK RIGHT-POINTING SMALL TRIANGLE
    $ent{'rtri'}        = chr(0x25B9);  #  WHITE RIGHT-POINTING SMALL TRIANGLE
    $ent{'dtrif'}       = chr(0x25BE);  #  BLACK DOWN-POINTING SMALL TRIANGLE
    $ent{'dtri'}        = chr(0x25BF);  #  WHITE DOWN-POINTING SMALL TRIANGLE
    $ent{'ltrif'}       = chr(0x25C2);  #  BLACK LEFT-POINTING SMALL TRIANGLE
    $ent{'ltri'}        = chr(0x25C3);  #  WHITE LEFT-POINTING SMALL TRIANGLE
    $ent{'loz'}         = chr(0x25CA);  #  LOZENGE
    $ent{'cir'}         = chr(0x25CB);  #  WHITE CIRCLE
    $ent{'starf'}       = chr(0x2605);  #  BLACK STAR
    $ent{'star'}        = chr(0x2606);  #  WHITE STAR
    $ent{'phone'}       = chr(0x260E);  #  BLACK TELEPHONE
    $ent{'female'}      = chr(0x2640);  #  FEMALE SIGN
    $ent{'male'}        = chr(0x2642);  #  MALE SIGN
    $ent{'spades'}      = chr(0x2660);  #  BLACK SPADE SUIT
    $ent{'clubs'}       = chr(0x2663);  #  BLACK CLUB SUIT
    $ent{'hearts'}      = chr(0x2665);  #  BLACK HEART SUIT
    $ent{'diams'}       = chr(0x2666);  #  BLACK DIAMOND SUIT
    $ent{'sung'}        = chr(0x266A);  #  EIGHTH NOTE
    $ent{'flat'}        = chr(0x266D);  #  MUSIC FLAT SIGN
    $ent{'natur'}       = chr(0x266E);  #  MUSIC NATURAL SIGN
    $ent{'sharp'}       = chr(0x266F);  #  MUSIC SHARP SIGN
    $ent{'check'}       = chr(0x2713);  #  CHECK MARK
    $ent{'cross'}       = chr(0x2717);  #  BALLOT X
    $ent{'malt'}        = chr(0x2720);  #  MALTESE CROSS
    $ent{'lozf'}        = chr(0x2726);  #  BLACK FOUR POINTED STAR
    $ent{'loz'}         = chr(0x2727);  #  WHITE FOUR POINTED STAR
    $ent{'sext'}        = chr(0x2736);  #  SIX POINTED BLACK STAR


    $ent{'fflig'}       = chr(0xFB00);  #  LATIN SMALL LIGATURE FF
    $ent{'filig'}       = chr(0xFB01);  #  LATIN SMALL LIGATURE FI
    $ent{'fllig'}       = chr(0xFB02);  #  LATIN SMALL LIGATURE FL
    $ent{'ffilig'}      = chr(0xFB03);  #  LATIN SMALL LIGATURE FFI
    $ent{'ffllig'}      = chr(0xFB04);  #  LATIN SMALL LIGATURE FFL


